develeep/Algorithm_study_7-2team

- minsun/BOJ/7568/sol.py
[BOJ] 7568:
- 문제 유형 : 구현
- 문제 난이도 : 백준 실버 5
- 시간복잡도 : O(N^2)
- 공간복잡도 : O(N)
```python
import sys
N = int(input()) # 사람의 수
people = []
result = []
a, b = map(int, input().split())
people.append((a, b))
cnt = 1
if people[i][0] < people[j][0] and people[i][1] < people[j][1]:
cnt+=1
result.append(cnt)
print(*result)
```
- 문제의 정답이 있다  만일 자신보다 더 큰 덩치의 사람이 k명이라면 그 사람의 덩치 등수는 k+1이 된다. 
- 비교하면서 큰 게 있으면 cnt+=1
> [Solve] : [BOJ] 7568 - 덩치 문제 해결

- seunghoon/BOJ/11559/sol.py
```python
def fall_down():
for y in range(weight):
for x in range(height - 1, -1, -1):
if grid[x][y] != '.':
i = x
while i + 1 < height:
if grid[i + 1][y] == '.':
grid[i][y], grid[i + 1][y] = grid[i + 1][y], grid[i][y]
i += 1
else:
break
dxy = ((1, 0), (-1, 0), (0, -1), (0, 1))
def check():
flag = 0
for i in range(height):
for j in range(weight):
if grid[i][j] != '.':
color = grid[i][j]
arr = set()
arr.add((i,j))
stack = [(i, j)]
while stack:
x, y = stack.pop()
if not (0 <= nx < height and 0 <= ny < weight):
continue
if (nx,ny) in arr:
continue
if grid[nx][ny] == color:
arr.add((nx,ny))
stack.append((nx, ny))
if len(arr) >= 4:
flag = 1
for ax, ay in arr:
grid[ax][ay] = '.'
if flag:
return 1
return 0
height = 12
weight = 6
grid = [[s for s in …
```
> [Solve] : [BOJ] 11559 - 백준 뿌요뿌요 문제 해결

- minsun/BOJ/2563/sol.py
[BOJ] 2563:
- 문제 유형 : 구현
- 문제 난이도 : 백준 실버 5
- 시간 : 36ms
- 내용 : https://www.acmicpc.net/problem/2563
- 아래 예시 참고
```python
**width, height= 100, 100
white_board = [[0] * width for _ in range(height)]
result = 0
count = int(input())
for _ in range(count):
x, y = map(int, input().split())
for i in range(x, x+10):
for j in range(y, y+10):
if white_board[i][j] == 1: continue
white_board[i][j] = 1
result+=1
print(result)**
```
- 밑에 사진과 같음
- 처음에 생각할 때 x+10, y+10으로 생각했는데 range(x, x+10)까지 하면 10까지는 포함 아니니까 11로 해야 하지 않나? 하고 x+11 로 하니까 답이 이상하게 나옴
> [Solve] : 색종이 문제 해결

- comet/BOJ/17143/sol.py
- comet/BOJ/17281/sol.py
- comet/BOJ/9251/sol.py
[LCS](https://www.acmicpc.net/problem/9251)
[야구공아이콘](https://www.acmicpc.net/problem/17281)
```python
def find():
first = '.' + input().strip()
second = '.' + input().strip()
if len(first) < len(second):
first, second = second, first
dp = [[0] * (len(second)) for _ in range(len(first))]
for i in range(1, len(first)):
temp = dp[i - 1][0]
for j in range(1, len(second)):
if first[i] == second[j]:
dp[i][j] = temp + 1
else:
dp[i][j] = dp[i - 1][j]
temp = max(temp, dp[i - 1][j])
return max(dp[-1])
print(find())
```
```python
def simulation(subset):
sunsu = deque(subset)
result = 0
for idx in arr:
rue = [0, 0, 0]
out = 0
while out < 3:
current = sunsu.popleft()
sunsu.append(current)
if idx[current] == 0:
out += 1
elif idx[current] == 1:
result += rue[2]
rue[2] = …
```
>  [Solved] : [BOJ] 9251 - LCS 문제풀이,  [Solved] : [BOJ] 17281 - 야구공아이콘 문제풀이

- minsun/BOJ/2559/sol.py
- 문제 유형 : 누적합
- 문제 난이도: 백준 실버 3
- 시간 : 68ms
- 내용 : https://www.acmicpc.net/problem/2559
```python
N, K = map(int, input().split())
arr = list(map(int, input().split()))
result = []
result.append(sum(arr[:K]))
for i in range(N-K):
result.append(result[i] - arr[i] + arr[K+i])
print(max(result))
```
- 문제 잘못 읽어서... 조금 오래 걸림
- 구간합은 왜 해도해도 제대로 못하지;;
> [Solve]: [BOJ] 2559 - 수열 문제 해결

- Minwoo/BOJ/2491/sol.py
- 제목 : [Solve] : [BOJ] 2491 - 수열 문제 해결
```python
import sys
def f(start, end, increase):
global result
case = 0
for i in range(start, end, increase):
if D[i] <= D[i + increase]:
case += 1
else:
result = max(result, case + 1)
case = 0
result = max(result, case + 1)
D = list(map(int, sys.stdin.readline().split()))
result = 0
f(0, N-1, 1)
f(N-1, 0, -1)
print(result)
```
- 정방향 순회와 역방향 순회로 가장 큰 수열을 찾습니다.
-  for문 끝날 때 수열이 증가하는 경우를 산정하지 않아 틀렸습니다.
> [Solve] : [BOJ] 2491 - 수열 문제 해결

- minseo/7568/sol.py
- 제목 : [Solve] : [BOJ] 7568 - 덩치 
- 아래 예시 참고
```python
big = []
people = int(input())
for p in range(people):
w,h = list(map(int,input().split()))
big.append([w,h])
cnt=1
for q in range(people):
max_w = big[q][0]
max_h = big[q][1]
for p in range(people):
if big[p][0] > max_w and big[p][1] > max_h:
cnt +=1
print(cnt,end=" ")
cnt = 1
```
- 키와 몸무게를 저장하여 배열을 만들고 하나씩 순회하였습니다. 
- 이때 순회할 때 자신보다 큰 값이 있으면 count 하고 출력하였습니다.
> [solve]: 덩치 7568 문제해결

- minseo/2559/sol.py
- 제목 : [Solve] : [BOJ] 2559 - 수열 
- 아래 예시 참고
```python
N , K = list(map(int,input().split()))
daytmp = list(map(int,input().split()))
sumtmp = 0
max_tmp = 0
current = sum(daytmp[:K])
max_tmp = current
for i in range(1,N - K + 1):
current = current - daytmp[i - 1] + daytmp[i + K - 1]
if current > max_tmp:
max_tmp = current
print(max_tmp)
```
- 온도의 합을 구하고 배열을 오른쪽으로 한 칸 밀면서,왼쪽 끝 값을 빼고(daytmp[i-1]) 새로 오른쪽에 추가된 값을 더하는 방식으로 구했습니다.(daytmp[i+K-1])
> [Solve] : 2559 수열 문제해결

- minseo/1789/sol.py
- 제목 : [solve] : [BOJ] 1789 - 수들의 합
- 아래 예시 참고
```python
sumnum = 0
count = 0
for i in range(1,n+1):
sumnum += i
if sumnum > n:
break
count +=1
print(count)
```
- 수들의 합을 이루는 개수의 최대 수를 구하는 방법이었습니다. 
- 핵심은 개수를 구하는 것이었습니다.
> [solve]:1789 문제 해결

- minseo/14501/sol.py
- 제목 : [solve] : [BOJ] 14501 - 퇴사 
- 아래 예시 참고
```python
days = []
moneys = []
daylen = int(input())
for d in range(daylen):
day,money = list(map(int,input().split()))
days.append(day)
moneys.append(money)
max_sum = 0
for t in range(daylen):
index = t
sum=0
while index < daylen:
if index >= daylen:
if sum >= max_sum:
max_sum = sum
break
sum += moneys[index]
index = t + days[t]
print(max_sum)
```
```
T : 상담을 완료하는데 걸리는 기간
P : 상담을 햇을 때 받을 수 있는 금액
기간 : [3,5,1,1,2,4,2]
돈 : [10,20,10,20,15,40,200]
0부터 T까지 순회 t
인덱스 = t(0,1)
while 인덱스 < 기간의 길이
if 인덱스 >= 기간[t]:
break
sum += 돈[인덱스](10,20)
인덱스 = t(1) + 기간[t](3,5)
(인덱스 6)
```
> [solve]: 14501 퇴사 문제해결

- Minwoo/BOJ/11399/sol.py
ATM 문제 해결
- 제목 : [Solve] : [BOJ] 11399 - ATM 문제 해결
- 문제 분류 : 그리디, 정렬
- 문제 난이도 : Silver 4
```python
arr = sorted(list(map(int, input().split())))
P = [arr[0]]
for i in range(1, N):
P.append(P[-1] + arr[i])
print(sum(P))
```
- 각 출금 손님들이 인출하는데 걸리는 시간을 최소화 하기 위해 오름차순 정렬
- 누적합으로 값을 저장한 뒤 총합을 출력
> [Solve] : [BOJ] 11399 - ATM 문제 해결

- Minwoo/BOJ/12927/sol.py
- 제목 : [Solve] : [BOJ] 12927 배수 스위치 - 문제 해결
- 문제 분류 : 그리디 알고리즘 ~~(왜?)~~
- 문제 난이도 : Silver 4
```python
def change(start, end, increase):
for i in range(start, end, increase):
arr[i] = 'N' if arr[i] == 'Y' else 'Y'
arr = list(input().strip())
N = len(arr)
cnt = 0
if arr[i] == 'Y':
change(i, N, i+1)
cnt += 1
print(cnt if N == arr.count("N") else -1)
```
- 스위치를 끄는 위치의 배수들의 스위치도 같이 꺼야 하므로 함수에서 increase라는 매개변수로 증가폭을 받아오게 됩니다.
- 최종적으로 출력은 모든 스위치가 꺼질 때, 스위치를 누른 횟수를, 모든 스위치가 꺼지지 않았다면 -1을 출력합니다.
- 이때 문제는 -1이 출력되는 경우가 없다는 것입니다. ~~문제 참...~~
> [Solve] : [BOJ] 12927 배수 스위치 - 문제 해결

- Minwoo/BOJ/2839/sol.py
- 제목 : [Solve] : [BOJ] 2839 설탕배달 - 문제 해결
- 문제 난이도 : Silver 4
- 문제 분류 : 수학, 다이나믹 프로그래밍(DP), Greedy
```python
kg5, now = divmod(N, 5)
kg3 = 0
ans = -1
while kg5 >= 0:
if now % 3 != 0:
kg5 -= 1
now += 5
else:
ans = kg5 + (now // 3)
break
print(ans)
```
- **`divmod`** : 나누고 싶은 숫자와 나눌 값을 넣으면, 몫과 나머지를 반환합니다.<br>
1. 일단 5KG 설탕 봉지를 가져갈 수 있는 최대와, 나머지를 확인합니다.
- 설탕의 무게에서 5를 나눈 몫은 5KG 설탕 봉지 수, 나머지는 남은 무게입니다.
2. 여기서 남은 설탕 무게로 3KG 봉지를 만들 수 있는지 확인합니다.
- 없을 경우 5KG 설탕을 터뜨려서 남은 설탕 무게에 합산합니다.
3. 최종적으로 무게를 맞췄다면, 봉지수를, 그럴 수 없다면 -1을 출력합니다.
- DP 문제라서 DP로도 풀어보면 좋을 것 같습니다.
> [Solve] : [BOJ] 2839 설탕배달 - 문제 해결

- kimchaejun/BOJ/2491/sol.py
- kimchaejun/BOJ/2527/sol.py
- kimchaejun/BOJ/7568/sol.py
- 제목 : [Solve] : [BOJ] 2527 - 직사각형 문제풀이
- 문제 링크 : https://www.acmicpc.net/problem/2527
```python
for i in range(4):
x1, y1, p1, q1, x2, y2, p2, q2 = list(map(int, input().split()))
if p1 < x2 or p2 < x1 or q1 < y2 or q2 < y1:
print('d')
elif (p1 == x2 and q1 == y2) or (p2 == x1 and q2 == y1) or (p1 == x2 and q2 == y1) or (p2 == x1 and q1 == y2):
print('c')
elif p1 == x2 or p2 == x1 or q1 == y2 or q2 == y1:
print('b')
else:
print('a')print('test')
```
- 두 사각형이 절대로 겹치지 않는 경우, 점끼리 겹치는 경우, 선끼리 겹치는 경우를 조건으로 구분한다.
- 조건에 따라서 'd', 'c', 'b'를 출력한다
- 위 모든 경우를 통과했다면, 두 직사각형이 겹친 부분은 반드시 직사각형이기 때문에 'a'를 출력한다.
> [Solve] : [BOJ] 2527 - 직사각형 문제풀이

- kimchaejun/BOJ/7568/sol.py
- 제목 : [Solve] : [BOJ] 덩치 문제 해결
- branch 만들어서 새로 올렸습니다.
```python
weights, heights = [], []
res = [1] * N
w, h = map(int, input().split())
weights.append(w)
heights.append(h)
if i == j:
continue
if weights[i] > weights[j] and heights[i] > heights[j]:
res[j] += 1
print(*res)
```
- 자기 자신과는 비교하지 않게, 예외처리를 한다.
- i번째 값이 덩치가 크다는 기준에 부합한다면, res[j] 값을 1 증가시킨다.
> [Solve] : [BOJ] 7568 문제 해결

- kimchaejun/BOJ/2491/sol.py
- kimchaejun/BOJ/7568/sol.py
- 제목 : [Solve] : 2491 수열 문제 해결
- 문제 링크 : https://www.acmicpc.net/problem/2491
```python
nums = list(map(int, input().split()))
std = nums[0]
low_cnt, high_cnt = 0, 0
tmp_low, tmp_high = 1, 1
for i in range(1, N):
if nums[i] > std:
tmp_high += 1
if tmp_low:
low_cnt = max(low_cnt, tmp_low)
tmp_low = 1
elif nums[i] < std:
tmp_low += 1
if tmp_high:
high_cnt = max(high_cnt, tmp_high)
tmp_high = 1
else:
tmp_low += 1
tmp_high += 1
low_cnt = max(low_cnt, tmp_low)
high_cnt = max(high_cnt, tmp_high)
std = nums[i]
low_cnt = max(low_cnt, tmp_low)
high_cnt = max(high_cnt, tmp_high)
print(max(high_cnt, low_cnt))
```
- nums[0]을 std 초기값으로 지정하고, 비교가 끝나면 std를 nums[i]로 갱신한다
- 오름차순 / 내림차순의 수열 길이를 저장하는 변수를 각각 선언한다.
- 수열이 증가하다 감소되면 high_cnt, 감소하다 증가하면 low_cnt 변수 …
> [Solve] : [BOJ] 2491 수열 문제 해결

- minseo/1181/sol.py
- 제목 : [solve] : [BOJ] 1181 
- 아래 예시 참고
```python
import sys
n = int(sys.stdin.readline().rstrip())
wordlist = [sys.stdin.readline().rstrip() for _ in range(n) ]
wordlist = list(set(wordlist))
wordlist.sort()
wordlist.sort(key=len)
for i in range(len(wordlist)):
print(wordlist[i])
```
- 중복 제거 > 사전순 > 길이순 정렬하는 것이 중요했습니다.
> [Solve] : 1181 문제 해결

- minseo/11650/sol.py
- 제목 : [solve] 11650 - 좌표 정렬하기 
- **문제 이름**:  좌표정렬하기 11650
- **플랫폼**:백준
- **문제 번호 / 링크**:  https://www.acmicpc.net/problem/11650
- **난이도**: 실버 5
- **푼 날짜**:  2024 / 04 / 05
```python
import sys
n = int(sys.stdin.readline())
coord = [tuple(map(int, sys.stdin.readline().split())) for _ in range(n)]
coord.sort(key=lambda x: (x[0], x[1]))
for x,y in coord:
print(x,y)
```
- 조건문으로 등장 횟수가 같은 값들을 필터링 후 정렬해서 2번째 값 출력
> [solve] 11650 문제해결

- minseo/2751/sol.py
- 제목 : [solve] 2751 - 수 정렬하기 2
- 아래 예시 참고
```python
import sys
n = int(sys.stdin.readline())
arr = []
arr.append(int(sys.stdin.readline()))
for num in sorted(arr):
print(num)
```
- input()은 시간이 오래걸린다는 얘기가 있어서 `int(sys.stdin.readline())` 를 사용했다. 
- sorted 와 sort의 차이를 잘 아는 것이 중요했다.
> [solve] 2751 문제 해결

- minseo/2108/sol.py
- 제목 : [solve] : [BOJ] 2108 - 통계학 
- **문제 이름**:통계학
- **플랫폼**: 백준  
- **문제 번호 / 링크**: https://www.acmicpc.net/problem/2108
- **난이도**: 실버 2
- **푼 날짜**: 2024 / 04 / 05  
```python
from collections import Counter
#시작점
numbers = [int(input()) for _ in range(n)]
arithmean = round(sum(numbers)/n)
numbers.sort(reverse=False)
median = numbers[n // 2]
modearr = Counter(numbers).most_common()
candidates = []
max_freq = modearr[0][1]
for key, val in modearr:
if val == max_freq:
candidates.append(key)
else:
break
candidates.sort()
mode = candidates[1] if len(candidates) > 1 else candidates[0]
#범위
max_num = max(numbers)
min_num = min(numbers)
scope = abs(max_num-min_num)
print(f"{arithmean}\n{median}\n{mode}\n{scope}")
```
n 은 홀수로 나온다.
1. 산술 평균: N개의 수들의 합 …
> [solve]:2108 통계학 문제 해결

- kimchaejun/BOJ/2491/sol.py
- kimchaejun/BOJ/2527/sol.py
- kimchaejun/BOJ/2559/sol.py
- kimchaejun/BOJ/7568/sol.py
- 제목 : [Solve] : [BOJ] 2559 - 수열 문제풀이
- 문제 링크 : https://www.acmicpc.net/problem/2559
```python
N, M = map(int, input().split())
temp = list(map(int, input().split()))
f_sum = sum(temp[:M])
res = f_sum
for i in range(M, N):
f_sum += temp[i] - temp[i-M]
res = max(res, f_sum)
print(res)
```
- 최초 구간합을 리스트 슬라이싱으로 구한다.
- 이전 값을 빼고, 현재 값을 더하며 구간합을 구하고, res를 최고값으로 갱신한다.
- 탐색 종료 후, res를 출력한다.
> [Solve] : [BOJ] 2559 - 수열 문제풀이

- comet/BOJ/1799/sol.py
- comet/BOJ/2133/sol.py
- comet/BOJ/2293/sol.py
- comet/BOJ/3954/sol.py
BOJ/2133 타일 채우기 
```python
def find(num):
if num % 2 == 1:
return 0
dp = [0] * (num + 1)
dp[0] = 1
dp[2] = 3
for i in range(4, num + 1, 2):
dp[i] = dp[i - 2] * 3
for j in range(4, i + 1, 2):
dp[i] += dp[i - j] * 2
return dp[num]
print(find(int(input())))
```
BOJ/1799 비숍
```python
def b_dfs(cnt, bishop):
if cnt == len(black):
global b_result
b_result = max(b_result, bishop)
return
y, x = black[cnt]
if not left_right[y - x] and not right_left[y + x]:
left_right[y - x] = 1
right_left[y + x] = 1
b_dfs(cnt + 1, bishop + 1)
left_right[y - x] = 0
right_left[y + x] = 0
b_dfs(cnt + 1, bishop)
def w_dfs(cnt, bishop):
if cnt == len(white):
global w_result
w_result = max(w_result, bishop)
return
y, x = white[cnt]
if not left_right[y - x] and not right_left[y + x]:
left_right[y - x] = 1
right_left[y + …
```
> [Solved] : BOJ/2133 타일 채우기 - 문제풀이

- .idea/Algorithm_study_7-2team.iml
- .idea/misc.xml
- jinhyeon/BOJ/15486/sol.py
[BOJ] 11559:
- 문제 유형 : dp
- 문제 난이도 : 백준 골드 4
- 시간 복잡도 : 1264ms
- 공간 복잡도 : 260mb
```python
import math
inf = -math.inf
dp = [0] * n
arr = [tuple(map(int, input().split())) for _ in range(n)]
max_val = 0
for i in range(n-1, -1, -1):
t, p = arr[i]
if i + t == n:
max_val = max(max_val, p)
dp[i] = max_val
continue
if i + t > n:
dp[i] = max_val
continue
dp[i] = dp[i+t] + p
max_val = max(max_val, dp[i])
dp[i] = max_val
print(max_val)
```
- 뒤쪽 인덱스부터 접근해서 최대값 초기화하고 넣는 방식으로 진행했습니다
> [Solve] 퇴사2 문제 해결

- minseo/BOJ/10158/sol.py
- 제목 : [Solve] : [BOJ] 개미 10158
- 내용 : 
[문제 링크](https://www.acmicpc.net/problem/10158)
```python
import sys
w,h = map(int,sys.stdin.readline().split())
x,y = map(int,sys.stdin.readline().split())
t = int(sys.stdin.readline().rstrip())
current_x = (x + t) % (2 * w)
current_y = (y + t) % (2 * h)
if current_x > w:
current_x = 2 * w - current_x
if current_y > h:
current_y = 2 * h - current_y
print(current_x,current_y)
```
- current_x와 current_y는 풀이 방식이 같습니다. 
```
만약 
6 - w
4 - x
27- t
일때
```
- current_x 는 이동한 거리의 좌표를 구하는 방법 
```current_x = (x + t) % (2 * w)```
- `x + t`에서 x는 시작 위치의 x, t는 한시간에 1칸씩 이동하니까 1*t. 이렇게 되면 끝도 없이 뚫고 나가니까
- 2 * w 는 0 을 기준으로 했을 때 왔다가 + 갔다가 = 총 2번이니까 곱해서 나머지를 구해주면(5-6-5-4-3-2-1-0-1-2-3-4-5-6-5-4-3-2-1-0..)
- 시작점을 기준으로 n바퀴 돈 후 나머지 부분에서 멈추게 됩니다. (1바퀴가 12번 이동한 값 / 31-24 = 7 …
> [solve]:10158문제해결

- JYJ/BOJ/10158/sol.py
- 제목 : [Solve] : [BOJ] 10158 개미-문제해결
- 아래 예시 참고
```python
w, h = map(int,input().split())
p, q = map(int,input().split())
t = int(input())
'''
시작위치에서 t 만큼 움직였을 때
12 나누기 6의 몫은 몇번 튕겼는지 알려주는거
p + t % w는 얘가 튕기고 나서도 몇칸 움직였는지 알려주는거
무조건 정방향으로 이동하니까 몫이 홀수
너비의 끝에서 몇칸 이동했는지 
짝수면 0에서 몇칸 움직였나
'''
if (p + t) // w % 2 == 0:
x = (p + t) % w
else:
x = w - (p + t) % w
if (q + t) // h % 2 == 0:
y = (q + t) % h
else:
y = h - (q + t) % h
print(x, y)
```
- 수식 써서 풀이했습니다 조건문에서 홀수면 최대 인덱스에서 감소 짝수면 0부터 증가
> [Solve] : [BOJ] 10158 개미-문제해결

- minsun/BOJ/10158/sol.py
[BOJ] 10158:
- 문제 유형 : 수학
- 문제 난이도 : 백준 실버 3
- 시간: 36ms
- 내용 : [문제 링크](https://www.acmicpc.net/problem/10158)
```python
w, h = map(int, input().split())
p, q = map(int, input().split())
t = int(input())
x = (p + t) % (2 * w)
y = (q + t) % (2 * h)
if x > w:
x = 2 * w - x
if y > h:
y = 2 * h - y
print(x, y)
```
- 처음에 생각한 방식 사진과 같음 
- if 네 개 걸어서 분기 처리하려고 함
- 하다가 못 하겠어서 풀이 봤어요 ㅜㅜ 
-
> [Solve] : [BOJ] 10158 개미 문제 해결

- hsr/boj/14501 퇴사/sol.py
- hsr/boj/뿌요뿌요/sol.py
[BOJ] 14501:
-문제유형:DP
-문제난이도:?
-시간복잡도:40ms
-공간복잡도:32412KB
- 제목 : [해결 여부] : [문제 사이트] 문제 번호 - 메세지
- 아래 예시 참고
```python
TP = [tuple(map(int, input().split())) for _ in range(N)]
dp = [0] * (N + 1)
for i in range(N - 1, -1, -1):
time, pay = TP[i]
if i + time <= N:
dp[i] = max(dp[i + 1], dp[i + time] + pay)
else:
dp[i] = dp[i + 1]
print(dp[0])
```
- DP로 접근해서 max값 갱신해가며 top - bottom 으로 풀었음
> [Solve] : 14501 퇴사

- kimchaejun/BOJ/1959/sol.py
- kimchaejun/BOJ/2491/sol.py
- kimchaejun/BOJ/2527/sol.py
- kimchaejun/BOJ/2559/sol.py
- kimchaejun/BOJ/2563/sol.py
- kimchaejun/BOJ/7568/sol.py
- 제목 : [Solve] : [BOJ] 2563 색종이 문제 해결
```python
fields = [[0]*100 for _ in range(100)]
x, y = map(int, input().split())
for i in range(x, x+10):
for j in range(y, y+10):
fields[i][j] = 1
res = 0
for i in range(100):
res += fields[i].count(1)
print(res)
```
- 100 * 100 사이즈의 배열 미리 생성한다.
- 입력된 x, y를 기점을 각각 10칸씩 이동해서 fields값 변경한다.
- res에 배열에 있는 1(색종이가 놓인 곳)의 개수를 전부 더하여 출력한다.
> [Solve] : [BOJ] 2563 색종이 문제 해결

- comet/BOJ/1038/sol.py
- comet/BOJ/1799/sol.py
- comet/BOJ/2133/sol.py
- comet/BOJ/2293/sol.py
- comet/BOJ/3954/sol.py
```python
#
dp = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
[0, 0, 1, 3, 6, 10, 15, 21, 28, 36],
[0, 0, 0, 1, 4, 10, 20, 35, 56, 84],
[0, 0, 0, 0, 1, 5, 15, 35, 70, 126],
[0, 0, 0, 0, 0, 1, 6, 21, 56, 126],
[0, 0, 0, 0, 0, 0, 1, 7, 28, 84],
[0, 0, 0, 0, 0, 0, 0, 1, 8, 36],
[0, 0, 0, 0, 0, 0, 0, 0, 1, 9],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]
result = [0, 10, 55, 175, 385, 637, 847, 967, 1012, 1022, 1023]
def find(dp, result, temp, num):
val = result[temp]
output = ''
idx = 9
for i in range(temp, 0, -1):
for j in range(idx, -1, -1):
if val - dp[i][j] < num:
output += str(j)
idx = j - 1
break
val -= dp[i][j]
return output
num = int(input()) + 1
temp = 0
if num <= 1023:
for i in range(1, len(result)):
if result[i] >= num:
temp = i
break …
```
> [Solved] : [BOJ] 1038 - 감소하는 수

- ImSeoHyun/BOJ/16918/sol.py
- ImSeoHyun/SWEA/특별한 정렬/sol.py
- ImSeoHyun/SWEA/파리퇴치/sol.py
- ImSeoHyun/SWEA/풍선팡/main.py
- ImSeoHyun/SWEA/풍선팡/sol.py
- 제목 : [solve] : [BOJ] 16918 봄버맨
- 내용 :  https://www.acmicpc.net/problem/16918
```python
def findResult(R, C, N, grid):
dx = [0, 0, -1, 1]
dy = [-1, 1, 0, 0]
def explode(map):
newMap = [['O'] * C for _ in range(R)]
for i in range(R):
for j in range(C):
if map[i][j] == 'O':
newMap[i][j] = '.'
for d in range(4):
ni, nj = i + dx[d], j + dy[d]
if 0 <= ni < R and 0 <= nj < C:
newMap[ni][nj] = '.'
return newMap
if N == 1:
return [''.join(row) for row in grid]
elif N % 2 == 0:
return ['O' * C for _ in range(R)]
else:
first = explode(grid)
if (N - 3) % 4 == 0:
return [''.join(row) for row in first]
else:
second = explode(first)
return [''.join(row) for row in second]
R, C, N = map(int, input().split())
grid = [list(input().strip()) for _ in range(R)]
result = findResult(R, C, N, grid)
for row in …
```
> [Solve] [BOJ] 16918 - 봄버맨

- kimchaejun/BOJ/16918/sol.py
- 제목 : [Solve] [BOJ] 16918 봄버맨 문제 해결
```python
import sys
N, M, TIMER = map(int, sys.stdin.readline().split())
bomb_set = [list(map(str, sys.stdin.readline().strip())) for _ in range(N)]
target_bomb = 'O'
dxy = [[0, 1], [0, -1], [1, 0], [-1, 0]]
def explosion(target):
to_clear = []
for ei in range(N):
for ej in range(M):
if bomb_set[ei][ej] == target:
to_clear.append((ei, ej))
for ei, ej in to_clear:
bomb_set[ei][ej] = '.'
ni, nj = ei + dx, ej + dy
if 0 <= ni < N and 0 <= nj < M and bomb_set[ni][nj] != target:
bomb_set[ni][nj] = '.'
for t in range(1, TIMER+1):
if t % 2 == 0:
if target_bomb == 'O':
bomb_set[i] = ['N' if bomb_set[i][j] == '.' else bomb_set[i][j] for j in range(M)]
else:
bomb_set[i] = ['O' if bomb_set[i][j] …
```
> [Solve] : [BOJ] 16918 봄버맨 문제 해결

- kimchaejun/BOJ/1038/sol.py
- kimchaejun/BOJ/16918/sol.py
- 제목 : [Solve] [BOJ] 1038 - 감소하는 수 문제풀이
```python
import sys
N = int(sys.stdin.readline())
nums = list(range(9, -1, -1))
cnt, res = 0, [0]
for i in range(1, 1024):
tmp = ''
for j in range(10):
if i & (1 << j):
tmp += str(nums[j])
res.append(int(tmp))
res = sorted(list(set(res)))
print(res[N] if N < len(res) else -1)
```
- 0~9 까지의 자연수를 중복 없이 사용하여 감소하는 수를 만들 수 있는 경우의 수는 한정적일 것이라 판단함
- 경우의 수가 한정적이다.  ->  부분 조합으로 구성 가능하다는 결론에 도달함.
- nums를 9부터 0까지 저장되게 만들어놓고, res에 0을 미리 추가한다.
- n개의 숫자로 만들 수 있는 부분 조합의 개수는 2ⁿ 개이다.
- 따라서 비트연산을 활용하여 부분조합을 구해서 res에 저장한다.
- res 안에 중복된 숫자가 있을 수도 있기 때문에, set를 하고, 오름차순으로 정렬한다.
- 입력받은 숫자 N이 res의 길이보다 크면 -1을, 그렇지 않으면 res[N]을 출력한다.
- O(1) ***단, 상수 10240만큼 연산이 실행된다.***
> [Solve] [BOJ] 1038 - 감소하는 수 문제풀이

- minseo/BOJ/16918/sol.py
- 제목 :  [FAIL] : [BOJ] 16918 봄버맨
- 내용 : 
- [문제링크](https://www.acmicpc.net/problem/16918)
```python
R, C, N = map(int, input().split())
grid = [list(input().strip()) for _ in range(R)]
allO = [['O'] * C for _ in range(R)]
boom1 = [['O'] * C for _ in range(R)]
for i in range(R):
for j in range(C):
if grid[i][j] == 'O':
boom1[i][j] = '.'  # 자기 자신 터짐
for dx, dy in [(-1,0),(1,0),(0,-1),(0,1)]:
ni = i + dx
nj = j + dy
if 0 <= ni < R and 0 <= nj < C:
boom1[ni][nj] = '.'
boom2 = [['O'] * C for _ in range(R)]
for i in range(R):
for j in range(C):
if boom1[i][j] == 'O':
boom2[i][j] = '.'
for dx, dy in [(-1,0),(1,0),(0,-1),(0,1)]:
ni = i + dx
nj = j + dy
if 0 <= ni < R and 0 <= nj < C:
boom2[ni][nj] = '.'
if N == 1:
for i in range(R):
print(''.join(grid[i]))  # 그냥 입력 그대로 출력
elif N % 2 == 0:
for i in …
```
> [fail]16918 봄버맨

- Minwoo/BOJ/1347/sol.py
- 제목 : [Solve] : [BOJ] 1347 미로만들기 - 문제 해결
- 난이도 : Silver 2
- 분류 : 시뮬레이션, 구현
```python
dx = [-1, 0, 1, 0]
note = list(input().strip())
dir = 2
x, y = 0, 0
location = [[x, y]]
if note[i] == "L":  # -1
dir = (dir - 1) if dir > 0 else 3
elif note[i] == "R": # +1
dir = (dir + 1) % 4
else:   # 좌표 이동
x, y = x + dx[dir], y + dy[dir]
location.append([x, y])
sort_x = sorted(location, key=lambda k: k[0])
sort_y = sorted(location, key=lambda k: k[1])
min_x  = sort_x[0][0]
min_y = sort_y[0][1]
if min_x < 0:
abs_x = abs(min_x)
for loc in location:
loc[0] += abs_x
if min_y < 0:
abs_y = abs(min_y)
for loc in location:
loc[1] += abs_y
R, C = sort_x[-1][0] + 1, sort_y[-1][1] + 1
grid = [['#'] * C for _ in range(R)]
for x, …
```
> [Solve] : [BOJ] 1347 미로만들기 - 문제 해결

- minsun/SWEA/22399/sol.py
[SWEA] 22399:
- 문제 난이도 : D3
- 시간 : 77ms
- 내용 : `[문제 링크](https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AZHLR0FKS4kDFAXd)`
```python
N = int(input()) #당근의 개수
karrot = list(map(int, input().split())) # 당근 크기
karrot.sort()
result = 9999999999
for i in range(1, N-1):
for j in range(i +1, N):
if karrot[i - 1] == karrot[i] or karrot[j - 1] == karrot[j]:
continue
s = i
m = j - i
l = N - j
min_k = min(s, m, l)
max_k = max(s, m, l)
diff = max_k - min_k
result = min(result, diff)
if result == 9999999999:
print(f'#{tc}', -1)
else:
print(f'#{tc}', result)
```
- 당근을 세 개로 나누기 위해서 for 문 돌려서 s,m, l max, min 값 찾아서 빼줌
-  if karrot[i - 1] == karrot[i] or karrot[j - 1] == karrot[j]: 이부분을 넣지 않았는데 그럼 2번째 테케 맞지 않음ㄴ .. 이부분은 마지막에 못 풀겠어서 찾아보긴 함 꼭 다시 …
> [Solve] : [SWEA] 22399 - 쉬운 당근 포장

- JYJ/BOJ/2563/sol.py
- 제목 : [Solve] : [BOJ] - 색종이 문제 해결
- 내용 :  풀이 코드, 풀이 방법 설명
```python
arr = [[0] * 101 for _ in range(101)]
result = 0
for k in range(n):
sekjong_ex, sekjong_ey = map(int,input().split())
for i in range(sekjong_ex, sekjong_ex + 10):
for j in range(sekjong_ey, sekjong_ey + 10):
arr[i][j] = 1
for i in range(len(arr)):
for j in range(len(arr)):
if arr[i][j] == 1:
result += 1
print(result)
```
- 이미 색종이의 가로와 세로 길이는 주어져 있음(10) 
빈 배열에 색종이의 시작점 부터 + 10까지 1로 만들고
배열에서 1의 개수를 세기
> [Solve] : [BOJ] - 색종이 문제 해결

- JYJ/BOJ/1347/sol.py
- 제목 : [Solve] : [BOJ] 미로만들기 - 문제해결
- 아래 예시 참고
```python
'''
F 는 앞으로 한칸 이동 
L과 R은 방향을 왼쪽 또는 오른쪽으로 전환
90도 회전은 하지만 위치는 그대로
x랑 y를 찾아서 #으로 된 배열 만들고
가는 곳 마다 .으로 바꾸면 될듯
'''
dx = [1, 0, -1, 0]
dy = [0, -1, 0, 1]
naeyong = list(input())
x = y = 0
xy = [[x, y]]
h = 0
if naeyong[i] == 'R':
h = (h + 1) % 4
elif naeyong[i] == 'L':
h = (h - 1) if h > 0 else 3
elif naeyong[i] == 'F':
x, y = x + dx[h], y + dy[h]
xy.append([x, y])
sx = sorted(xy, key=lambda k: k[0])
sy = sorted(xy, key=lambda k: k[1])
minx = sx[0][0]
miny = sy[0][1]
if minx < 0:
minx1 = abs(minx)
for i in range(len(sx)):
sx[i][0] += minx1
if miny < 0:
miny1 = abs(miny)
for i in range(len(sy)):
sy[i][1] += miny1
q, p = sx[-1][0] + 1, sy[-1][1] + 1
arr = [['#'] * p for _ in …
```
> [Solve] : [BOJ] 미로만들기

- Minwoo/BOJ/16918/sol.py
- 제목 : [Solve] : [BOJ] 16918 봄버맨 - 문제해결
- 난이도 : Silver 1
- 분류 : 시뮬레이션, 구현
```python
"""
1. 일부 칸에 폭탄을 설치해 놓는다, 모든 폭탄이 설치된 시간은 같다(0초)
2. 다음 1초 동안 봄버맨은 아무것도 하지 않는다.(1초)(입력값 출력)
3. 다음 1초 동안 폭탄이 설치외어 있지 않은 모든 칸에 폭탄을 설치한다.
-> 풀배열 (2초 후)
4. 1초가 지난 후에 3초 전 설치된 폭탄이 모두 폭발한다(3초 후)
5. 3과 4를 반복한다.
"""
dkx = (1, 0, -1, 0)
dky = (0, 1, 0, -1)
def bomb(check_grid):
bomb_grid = set_bomb()
for x in range(R):
for y in range(C):
if check_grid[x][y] == 'O':
bomb_grid[x][y] = '.'
for dx, dy in zip(dkx, dky):
if not (0 <= nx < R and 0 <= ny < C):
continue
bomb_grid[nx][ny] = '.'
return bomb_grid
def set_bomb():
temp = [['O'] * C for _ in range(R)]
return temp
def printing(print_grid):
for li in print_grid:
print(''.join(li))
R, C, N = map(int, …
```
> [Solve] : [BOJ] 16918 봄버맨 - 문제해결

- Minwoo/BOJ/13305/sol.py
- 제목 : [Solve] : [BOJ] 13305 주유소 - 문제 해결
- 문제 난이도 : Silver 3
- 문제 분류 : Greedy
```python
import sys
road = list(map(int, sys.stdin.readline().split()))
station = list(map(int, sys.stdin.readline().split()))
result = station[0] * road[0]
min_cost = station[0]
for i in range(1, N-1):
if min_cost > station[i]:
min_cost = station[i]
result += (min_cost * road[i])
print(result)
```
1. 무조건 시작점에서 이동을 해야 합니다.
2. 현재 min_cost와 다음 도시의 주유소 가격을 비교합니다.
- 만약 다음 도시 주유소 가격이 낮다면, min_cost를 갱신합니다.
- 그렇지 않다면, 이전 주유소에서 주유했다고 생각합니다.
3. 최종적으로 갱신과 누적을 반복했던 result를 출력합니다.
- 조언을 들었습니다.
- 다시 풀어볼 예정입니다.
> [Solve] : [BOJ] 13305 주유소 - 문제 해결

- comet/BOJ/1799/sol.py
- comet/BOJ/20056/sol.py
- comet/BOJ/2133/sol.py
- comet/BOJ/2293/sol.py
- comet/BOJ/3954/sol.py
```python
def select(arr):
before = fireball[arr[0]][direc] % 2
for i in arr:
if before != fireball[i][direc] % 2:
return False
return True
y = 0
x = 1
mass = 2
speed = 3
direc = 4
length, num, turns = map(int, input().split())
fireball = {}
result = 0
grid = {}
div = length - 1
idx = num + 1
for i in range(length):
for j in range(length):
grid[(i, j)] = []
for i in range(1, num + 1):
fireball[i] = list(map(int, input().split()))
fireball[i][0] -= 1
fireball[i][1] -= 1
grid[(fireball[i][0], fireball[i][1])].append(i)
for turn in range(turns):
temp = []
for fire in fireball.keys():    # 파이어볼 이동
grid[(fireball[fire][y], fireball[fire][x])].remove(fire)
if fireball[fire][direc] == 0:
fireball[fire][y] -= fireball[fire][speed]
fireball[fire][y] %= length
if fireball[fire][y] < 0: …
```
> [Solved] : [BOJ] 20056 - 마법사 상어와 파이어볼 문제 해결

- minseo/BOJ/1347/sol.py
- 제목 : [Solve] : [BOJ] 1347 - 미로만들기 
- 아래 예시 참고
```python
import sys
n = int(sys.stdin.readline().rstrip())
arr = list(sys.stdin.readline().rstrip())
direction=[[1,0],[0,-1],[-1,0],[0,1]]
current_direct = 0
x,y = 0,0
visited = [(x,y)]
for m in range(len(arr)):
if arr[m] == 'L':
current_direct = (current_direct - 1) % 4
if arr[m] == 'R':
current_direct = (current_direct + 1) % 4
if arr[m] == 'F':
#현재 위치 좌표 변경(이부분에서 많이 헤맸다 )
dx,dy = direction[current_direct]
x += dx
y += dy
#좌표 저장 리스트에 넣기
visited.append((x,y))
row = [p[0] for p in visited]
max_x =  max(row)
min_x = min(row)
col = [p[1] for p in visited]
max_y = max(col)
min_y = min(col)
height = max_x - min_x + 1
width = max_y - min_y + 1
result = [['#'] * width for _ in range(height)]
for vx,vy in visited:
#가장 …
```
> [Solve] 1347 미로만들기 문제 해결

- JJangDongHyeon/20056/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/20056)
- 
```python
from collections import defaultdict
dx = [-1, -1, 0, 1, 1, 1, 0, -1]
dy = [0, 1, 1, 1, 0, -1, -1, -1]
n, M, k = map(int, input().split())
fire_ball_arr = [[[] for _ in range(n)] for _ in range(n)]
for _ in range(M):
r, c, jilyiang, sokryiock, banghyang = map(int, input().split())
fire_ball_arr[r - 1][c - 1].append((jilyiang, sokryiock, banghyang))
for _ in range(k):
new_arr = [[[] for _ in range(n)] for _ in range(n)]
for j in range(n):
for jilyiang, sokryiock, banghyang in fire_ball_arr[i][j]:
ni = (i + dx[banghyang] * sokryiock) % n
nj = (j + dy[banghyang] * sokryiock) % n
new_arr[ni][nj].append((jilyiang, sokryiock, banghyang))
for j in range(n):
if len(new_arr[i][j]) >= 2: …
```
> [Solve] : 마법사 상어와 파이어볼 문제 해결

- Minwoo/BOJ/20056/sol.py
- 제목 : [Solve] : [BOJ] 20056 마법사 상어와 파이어볼 - 문제 해결
- 난이도 : Gold 4
- 분류 : 시뮬레이션, 구현
- Runtime : python일 때 444 / pypy일 때 356ms
```python
import sys
dx = [-1, -1, 0, 1, 1, 1, 0, -1]
dy = [0, 1, 1, 1, 0, -1, -1, -1]
def is_valid(nrow, ncol):
if nrow >= N:
nrow %= N
elif nrow < 0:
nrow = (N + nrow) % N
if ncol >= N:
ncol %= N
elif ncol < 0:
ncol = (N + ncol) % N
return nrow, ncol
def assembly(data_list, x, y):
cnt = len(data_list)
odd, even = 0, 0
sum_mass, sum_speed = 0, 0
for temp in data_list:
sum_mass += temp[2]
sum_speed += temp[3]
if temp[4] % 2 == 0:
even += 1
else:
odd += 1
div_mass = sum_mass // 5
div_speed = sum_speed // cnt
if div_mass == 0:
return
if odd == cnt or even == cnt:
for dir in range(0, 7, 2):
data.append([x, y, …
```
> [Solve] : [BOJ] 20056 마법사 상어와 파이어볼 - 문제 해결

- minseo/BOJ/14729/sol.py
- 제목 : [Solve] : [BOJ] 14729 - 칠무해  
- 아래 예시 참고
```python
import sys
n = int(sys.stdin.readline())
score = [float(sys.stdin.readline().rstrip()) for i in range(n)]
score.sort(reverse=False)
for i in range(7):
print(f"{score[i]:.3f}")
```
>입력값 
n = 개수
score = 점수 배열
>문제 
배열 순회 하면서
오름차순 정렬
7명만 출력
> [Solve][BOJ] 칠무해 문제 해결

- comet/BOJ/1799/sol.py
- comet/BOJ/1915/sol.py
- comet/BOJ/2133/sol.py
- comet/BOJ/2293/sol.py
- comet/BOJ/3954/sol.py
난이도 : 골드 4
문제 유형 : DP
```python
def find(width, length, arr):
max_val = -9999
for i in range(1, width):
for j in range(1, length):
if arr[i][j] and arr[i-1][j-1] and arr[i][j-1] and arr[i-1][j]:
arr[i][j] += min(arr[i][j-1], arr[i-1][j], arr[i-1][j-1])
for i in arr:
max_val = max(max_val, max(i))
return max_val ** 2
width, length = map(int, input().split())
arr = [list(map(int, list(input().strip()))) for _ in range(width)]
print(find(width, length, arr))
```
- 왼쪽칸 윗칸, 북서쪽 칸이 다 1이상인지 확인(사각형이 만들어질 수 있는지)
- 맞다면 3칸중 최소값을 현재값에 추가 (만들어질 수 있는정사각형의 변의 길이를 구함)
- 최댓값을 찾아 제곱하여 출력!
>  [Solved] : [BOJ] 1915 - 가장 큰 정사각형 문제 해결

- Minwoo/BOJ/16236/sol.py
- 제목 : [Solve] : [BOJ] 16236 아기상어 - 문제 해결
- 난이도 : Gold 3
- 분류 : 그래프 탐색, 너비우선탐색(BFS), 시뮬레이션
- Runtime: python의 경우 176ms
```python
dkx = [-1, 0, 0, 1]
dky = [0, -1, 1, 0]
def fish_count():
global location, grid, now_x, now_y, size
temp = 0
if grid[i][j] == 9:
now_x, now_y = i, j
elif 0 < grid[i][j] < size:
temp += 1
location.add((i, j))
return temp
def BFS(sx, sy):
global location, N, size
visited = [[False] * N for _ in range(N)]
queue = deque([[sx, sy, 0]])
visited[sx][sy] = True
temp = []
grid[sx][sy] = 0
while queue:
x, y, t = queue.popleft()
t += 1
for dx, dy in zip(dkx, dky):
if not(0 <= nx < N and 0 <= ny < N) or visited[nx][ny]: continue
if grid[nx][ny] > size: …
```
> [Solve] : [BOJ] 16236 아기상어 - 문제 해결

- minsun/BOJ/1244/1244.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/1244)
```python
switch = list(map(int,input().split()))
student_N = int(input())
for i in range(student_N):
gender, switch_N = map(int, input().split())
if gender == 1:
for s in range(1, N + 1):
if s % switch_N == 0:
if switch[s-1] == 1:
switch[s-1] = 0
else:
switch[s-1] = 1
else:
left = switch_N-2
right = switch_N
while left >= 0 and right < N:
if switch[left] != switch[right]:
break
left -=1
right +=1
for j in range(left+1, right):
if switch[j] == 1:
switch[j] = 0
else:
switch[j] = 1
for k in range(N):
print(switch[k], end = " ")
if (k+1) % 20 == 0 :
print()
```
- 남자는 그냥 배수를 바꾸면 되는 거여서 %n 으로 했습니다
- 여자는 대칭인 부분을 다 바꿔야 하는데 이게 인덱스가 0부터 시작해서 접근이 생각보다 어려웠습니다
> [Solve] : [BOJ] 1244 스위치 켜고 끄기 문제 해결

- Minwoo/SWEA/22399/sol.py
- 제목 : [Solve] : [SWEA] 22399 쉬운 당근 포장하기 - 문제 해결
- 난이도 : D3
- 풀이방법 : 완전 탐색
```python 
carrot = list(map(int, input().split()))
carrot_box = [0] * 31
for i in carrot:
carrot_box[i] += 1
result = float('inf')
for i in range(31):
for j in range(i, 31):
small, middle, big = sum(carrot_box[:i]), sum(carrot_box[i:j]), sum(carrot_box[j:])
temp = [small, middle, big]
if 0 in temp:
continue
case = max(temp) - min(temp)
result = min(result, case)
print(f'#{tc}', result if result != float('inf') else -1)
```
```python
def is_valid(s, m, b):
global result
if not s or not m or not b:
return -1
if s[-1] == m[0] or m[-1] == b[0]:
return -1
temp = [len(s), len(m), len(b)]
value = max(temp) - min(temp)
if value > …
```
> [Solve] : [SWEA] 22399 쉬운 당근 포장하기 - 문제 해결

- kimchaejun/BOJ/18870/sol.py
```python
pos = list(map(int, input().split()))
pos_compress = sorted(set(pos))
pos_dict = {}
for i in range(len(pos_compress)):
pos_dict.setdefault(pos_compress[i], i)
pos = [str(pos_dict[p]) for p in pos]
print(' '.join(pos))
```
```python
pos = list(map(int, input().split()))
pos_compress = sorted(set(pos))
pos_dict = {v: i for i, v in enumerate(pos_compress)}
print(' '.join([str(pos_dict[p]) for p in pos]))
```
- 입력받은 좌표를 set로 합친 뒤, 오름차순으로 정렬한다.
- 정렬된 좌표값을 key, 정렬된 인덱스 번호를 value로 딕셔너리를 만든다.
- 첫 입력을 돌면서 저장되어있는 좌표의 인덱스 번호를 문자열로 다시 배열에 저장한다.
- join을 사용하여 한번에 정리한 후 출력한다.
- ***__2번째 코드는 리스트 컴프리헨션으로 정리해봤습니다. (동작 원리는 동일)__***
- 최악, 평균 : O(N log N) (실행시간에선 차이가 발생함)
- 최선 : O(N) (모든 좌표가 같으면)
> [Solve] : [BOJ] 18870 - 좌표압축 문제 해결

- kimchaejun/BOJ/2149/sol.py
- kimchaejun/SWEA/22399/sol.py
- 제목 : [Solve] : [SWEA] 22399 - 쉬운 당근 포장 문제 해결
```python
carrot = list(map(int, input().split()))
carrot_cnt = [0] * 31
res, tmp = float('inf'), 0
for c in carrot:
carrot_cnt[c] += 1
for i in range(1, 31):
for j in range(i, 31):
S, M, L = sum(carrot_cnt[:i]), sum(carrot_cnt[i:j]), sum(carrot_cnt[j:])
if not (S == 0 or M == 0 or L == 0):
tmp = max(S, M, L) - min(S, M, L)
res = min(tmp, res)
print(f"#{tc} {res if res != float('inf') else -1}")
```
- 구간합을 이용하여 모든 경우의 수를 탐색한다.
- 당근이 0개인 상자가 없는 경우에만 tmp를 계산하여 최솟값을 갱신한다.
- res값이 초기값인 float('inf')라면 -1을, 그렇지 않다면 res 값을 출력한다
- 최악 : O(N + 900) ≈ O(N)
- 평균 : O(N + 900)
- 최선 : O(N)
> [Solve] : [SWEA] 22399 - 쉬운 당근 포장 문제 해결

- kimchaejun/BOJ/2149/sol.py
- 제목 : [BOJ] 2149 - 암호해독 문제 해결
```python
key = str(input()) # 이건 제가 C로 공부할 때 버릇 들어서... 앞으로 조심하겠습니다.
code = str(input())
key_len, code_len = len(key), len(code)
ck_len = code_len // key_len
sort_key = sorted(key)
visited = [False] * key_len
code_pattern, res = [], []
for i in range(0, code_len, ck_len):
code_pattern.append([sort_key[i//ck_len], code[i:i+ck_len]])
for k in key:
for i in range(key_len):
if code_pattern[i][0] == k and not visited[i]:
visited[i] = True
res.append(code_pattern[i][1])
break
for i in range(ck_len):
for j in range(key_len):
print(res[j][i], end='')
```
- 주어진 문장은 암호 해독 키와 암호문이다.
- 따라서, 역산으로 암호 해독 키의 전과정을 만든다.
- 암호 키의 글자 순서에 맞게끔 정렬한다. (같은 글자가 들어올 경우를 대비)
- 글자를 하나씩 순대로 출력한다.
- 최선 : O(key_len log key_len + code_len)
- 평균 : O(key_len² + …
> [Solve] : [BOJ] 2149 - 암호해독 문제 해결

- Minwoo/BOJ/6593/sol.py
- 제목 : [Solve] : [BOJ] 6593 상범 빌딩 - 문제 해결
- 난이도 : Gold 5
- 분류 : 너비 우선 탐색
```python
def BFS():
global stf, stx, sty, building, R, C, L, result
visited = [[[False] * C for _ in range(R)] for __ in range(L)]
dkx = [1, 0, -1, 0]
dky = [0, -1, 0, 1]
queue = deque([[stf, stx, sty, 0]])
visited[stf][stx][sty] = True
while queue:
f, x, y, cnt = queue.popleft()
if building[f][x][y] == 'E':
result = min(result, cnt)
continue
cnt += 1
next_f, prev_f = f + 1, f - 1
if next_f < L and not visited[next_f][x][y]:
if building[next_f][x][y] in ['.', 'E']:
queue.append([next_f, x, y, cnt])
visited[next_f][x][y] = True
if prev_f >= 0 and not visited[prev_f][x][y]:
if building[prev_f][x][y] in ['.', 'E']:
queue.append([prev_f, x, y, cnt]) …
```
> [Solve] : [BOJ] 6593 상범 빌딩 - 문제 해결

- minsun/BOJ/10789/sol.py
[BOJ] 10789:
- 문제 유형 : 구현
- 문제 난이도 : 백준 브론즈 1
- 시간 : 36ms
- 내용 : [문제 링크](https://www.acmicpc.net/problem/10798)
```python
N = 5
matrix = [list(map(str, input().strip())) for _ in range(N)]
for i in range(15):
for j in range(5):
if i < len(matrix[j]):
print(matrix[j][i], end="")
```
> [Solve] : BOJ 10789 - 세로 읽기 문제 해결

- minsun/BOJ/10026/sol.py
[BOJ] 10026:
- 문제 유형 : BFS
- 문제 난이도 : 백준 골드 5
- 시간 : 72ms
- 내용 : [문제 링크](https://www.acmicpc.net/problem/10026)
```python
import sys
dxy = [[0, -1], [0, 1], [1, 0], [-1, 0]]
def view_rgb(start_x, start_y, rgb):
queue = deque()
queue.append((start_x, start_y))
visited[start_x][start_y] = 1
while queue:
x, y = queue.popleft()
nx = x + dx
ny = y + dy
if 0 <= nx < N and 0 <= ny < N and visited[nx][ny] != 1:
if rgb == matrix[nx][ny]:
queue.append((nx,ny))
visited[nx][ny] = 1
def change_rgb():
if matrix[i][j] == 'R':
matrix[i][j] = 'G'
matrix = [list(map(str, input().strip())) for _ in range(N)]
visited = [[0]* N for _ in range(N)]
result = 0
result2 = 0
for …
```
> [Solve] : [BOJ] 10026 - 적록색약 문제 해결

- Minwoo/BOJ/10026/sol.py
- 제목 : [Solve] : [BOJ] 10026 적록색약 - 문제 해결
- 문제 난이도 : Gold 5
- 문제 유형 : 너비 우선 탐색
```python
dkx = [1, 0, -1, 0]
dky = [0, 1, 0, -1]
def traversal(data):
global N
visited = [[False] * N for _ in range(N)]
def BFS(x, y, color):
nonlocal visited, data
queue = deque([(x, y)])
visited[x][y] = True
while queue:
x, y = queue.popleft()
for dx, dy in zip(dkx, dky):
if not(0 <= nx < N and 0 <= ny < N):
continue
if visited[nx][ny]: continue
if data[nx][ny] != color: continue
queue.append((nx, ny))
visited[nx][ny] = True
cnt = 0
if not visited[i][j]:
BFS(i, j, data[i][j])
cnt += 1
return cnt
def change_color():
global data2
if data2[i][j] == 'G': …
```
> [Solve] : [BOJ] 10026 적록색약 - 문제 해결

- JYJ/SWEA/22654/sol.py
[Solve] : [SWEA] 22654 차윤이의 RC카 - 문제해결
https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AZIx55YKpg0DFAQP
```python
'''
G : 이동 가능한 땅
T : 이동 불가능한 나무
X : 현재 RC카의 위치
Y : RC 카를 이동시키고자 하는 위치
동작
A : 앞으로 이동 - 나무나 필드를 벗어나는 경우 아무일도 일어나지 않는다
L : 현재 바라보고 있는 방향에서 왼쪽으로 90도 회전
R : 현재 바라보고 있는 방향에서 오른쪽으로 90도 회전
'''
def x(): # arr에서 x를 찾는 함수
for j in range(n):
if arr[i][j] == 'X':
return i, j
dx = [-1, 0, 1, 0] # 위 오 아 왼
T = int(input())   # Test case 개수를 받아오는 코드
arr = [list(input()) for _ in range(n)]
q = int(input())
result = []
for _ in range(q):
c, commend = map(str,input().split())
idx = 0
i, j = x()
for k in commend:
if k == 'R': # 델타에서 방향을 지정해놓고 들어가기
idx …
```
> [Solve] : [SWEA] 22654 차윤이의 RC카 - 문제해결

- comet/SWEA/3951/sol.py
#[CRT](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWH-Dma6EgEDFAUG)
```python
def find(question, num):
if num == 1:
return question[0][0]
temp, div= question.pop()
while 1:
for a, b in question:
if temp % b != a:
break
else:
return temp
temp += div
num = int(input())
question = [list(map(int, input().split())) for _ in range(num)]
question.sort(key=lambda x: x[1])
result = find(question, num)
print(f'#{tc} {result}')
```
- 입력값을 받아 나누는 값(Ni) 을 기준으로 정렬.
- 큰 값부터 확인해나가면 가능성을 큰 폭으로 줄여나갈 수 있음.
-  현재 값 % N 이 B 인지 확인하며 아니면 바로 다음 값으로 넘어감.
> [Solved] : SWEA/3951 CRT 문제 해결

- comet/BOJ/17406/sol.py
난이도 : 골드 4
유형 : 브루트포스
```python
def find(cnt, arr):
global visit, num, rotate, result
if cnt == num:
for idx in arr:
result = min(result, sum(idx))
return
for k in range(num):
if not visit[k]:
new_arr = [idx[:] for idx in arr]
for l in range((rotate[k][1] - rotate[k][0]) // 2):
for x in range(rotate[k][2] + 1 + l, rotate[k][3] - l + 1):
new_arr[rotate[k][0] + l][x] = arr[rotate[k][0] + l][x - 1]
for x in range(rotate[k][2] + l, rotate[k][3] - l):
new_arr[rotate[k][1] - l][x] = arr[rotate[k][1] - l][x + 1]
for y in range(rotate[k][0] + 1 + l, rotate[k][1] - l + 1):
new_arr[y][rotate[k][3] - l] = arr[y - 1][rotate[k][3] - l]
for y in range(rotate[k][0] + l, rotate[k][1] - l):
new_arr[y][rotate[k][2] + l] = arr[y + 1][rotate[k][2] + l]
visit[k] = 1
find(cnt + 1, new_arr)
visit[k] = 0
width, …
```
> [BOJ] : 17406 배열  돌리기 문제 해결

- minsun/BOJ/13305/sol.py
[BOJ] 13305:
- 문제 유형 : 그리디
- 문제 난이도 : 백준 실버 3
- 시간 : 100ms
- 내용 : [문제 링크](https://www.acmicpc.net/problem/13305)
```python
import sys
N = int(input()) # 도시의 개수를 나타내는 정수
city = list(map(int,input().split()))
cost = list(map(int, input().split()))
min_cost = 999999999
result = 0
for i in range(N-1):
if cost[i] < min_cost:
min_cost = cost[i]
result += (min_cost * city[i])
print(result)
```
- min_cost 를 저장하고 도시의 간선? 만큼 for문 돈다
- 가장 작은 cost를 찾고 가야할만큼 곱해주면 됨
> [Solve] : [BOJ] 13305 - 주유소 문제해결

- JYJ/SWEA/22399/sol.py
[Solve] : [SWEA] 22399 쉬운 당근 포장 - 문제 해결
- 내용 :  풀이 코드, 풀이 방법 설명
https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AZHLR0FKS4kDFAXd&categoryId=AZHLR0FKS4kDFAXd&categoryType=CODE 
```python
'''
n개의 당근을 주문하면 대, 중, 소 상자로 구분한다
비어있는 상자가 있으면 안 된다
각 상자에 든 당근의 개수 차이가 최소가 되도록 포장해야 한다
한 바구니에 같은 당근 담을거니까 개수 세서 집어넣는다
'''
T = int(input())   # Test case 개수를 받아오는 코드
carrot_size = list(map(int,input().split()))
pojang = [0] * 31
result = float('inf')
pojang[carrot_size[i]] += 1
count = []
for i in pojang:
if i > 0:
count.append(i)
for i in range(len(count)):
for j in range(i, len(count)):
a = sum(count[:i])
b = sum(count[i:j])
c = sum(count[j:])
if a > 0 and b > 0 and c > 0:
d = max(a, b, c) - min(a, b, c)
if d …
```
> [Solve] : [SWEA] 22399 쉬운 당근 포장 - 문제 해결

- JYJ/BOJ/2999/sol.py
- [Solve] : [BOJ] 2999 비밀 이메일 - 문제 해결
- 내용 : 풀이 코드, 풀이 방법 설명
```python
'''
r <= C 이고 r*c = n 인 r과 c를 고른다
그러한 경우가 여러 개일 경우 r이 큰 값을 선택한다
그 다음 행이 r개고 열이 c 개인 행렬을 만든다
행렬에 모두 메시지를 옮겼다면, 이 것을 첫 번째 열의 첫 번째 행부터
r 번째 행 까지 차례대로 읽으면서 받아적는다
'''
def rnc(): # 조건에 맞는 r과 c를 찾는 함수
r = c = 0
for i in range(1, n + 1):
for j in range(1, n + 1):
if i <= j and i * j == n:
if r < i:
r, c = i, j
return r, c
word = list(input())
n = len(word)
r, c = rnc()
idx = 0
arr = [[''] * r for _ in range(c)]
result = []
for i in range(c): # 하나씩 배열에 추가
for j in range(r):
arr[i][j] = word[idx]
idx += 1
for i in range(r): # 배열 다시 읽기
for j in range(c):
result.append(arr[j][i])
for i in result:
print(''.join(i), end='')
```
- 조건에 맞는 r, c를 찾고 배열 만들고 배열에 문자 작성 후 새로운 배열로 조건에 맞게 추가 후 프린트
시간 복잡도나 공간 복잡도를 아낄 수 있는 더 좋은 방법이 있다면 좋아요와 구독
> [Solve] : [BOJ] 2999 비밀 이메일 - 문제 해결

- Minwoo/SWEA/22654/sol.py
- 제목 : [Solve] : [SWEA] 22654 차윤이의 RC카 - 문제 해결
- 문제 난이도 : D2
- 문제 해결 방법 : 완전 탐색
```python
dx = [-1, 0, 1, 0]
def is_valid(commends):
global sx, sy, grid, N
x, y = sx, sy
d = 0
for cmd in commends:
if cmd == 'R':
d = (d + 1) % 4
elif cmd == 'L':
d = (d - 1) if d > 0 else 3
else:
nx, ny = x + dx[d], y + dy[d]
if not(0 <= nx < N and 0 <= ny < N): continue
if grid[nx][ny] == 'T': continue
x, y = nx, ny
if grid[x][y] == 'Y':
return 1
return 0
def check():
global grid
if grid[i][j] == 'X':
return i, j
grid = [list(input().strip()) for _ in range(N)]
sx, sy = check()
result = []
Q = int(input())
for q in range(Q):
C, commend = input().split()
commend = …
```
> [Solve] : [SWEA] 22654 차윤이의 RC카 - 문제 해결

- minsun/BOJ/2527/sol.py
[BOJ] 2527:
- 문제 유형 : 수학
- 문제 난이도 : 백준 실버 1
- 시간 : 32ms
- 내용 : [문제 링크](https://www.acmicpc.net/problem/2527)
```python
for _ in range(4):
x1, y1, p1, q1, x2, y2, p2, q2 = map(int, input().split())
"""
a - 겹침
b - 선으로 겹침
c - 점으로 겹침
d - 안 겹침
"""
if p1 < x2 or p2 < x1 or y1 > q2 or q1 < y2:
print('d')
elif (x2 == p1 and y2 == q1) or (x2 == p1 and y1 == q2) or (x1 == p2 and y1 == q2) or (x1 == p2 and y2 == q1):
print('c')
elif p1 == x2 or x1 == p2 or y1 == q2 or y2 == q1:
print('b')
else:
print('a')
```
- 조건분기 그만하고 싶어요
> [Solve] : [BOJ] 2527 - 직사각형 문제 해결

- comet/BOJ/17472/sol.py
[17472](https://www.acmicpc.net/problem/17472)
난이도 : 골드 1
유형 : 브루트포스, 그래프탐색, 넓이 우선 탐색
```python
def bfs(i, j, arr, visit, island):
que = deque([(i, j)])
visit[i][j] = 1
arr[i][j] = island
while que:
cur_y, cur_x = que.popleft()
for dy, dx in [(-1, 0), (0, -1), (1, 0), (0, 1)]:
tempy = cur_y + dy
tempx = cur_x + dx
if 0 <= tempy < width and 0 <= tempx < length and arr[tempy][tempx] and not visit[tempy][tempx]:
arr[tempy][tempx] = island
visit[tempy][tempx] = 1
que.append((tempy, tempx))
def find(y, x, dy, dx, cur):
global arr, bridge
cnt = 1
tempy, tempx = y, x
while 1:
tempy += dy
tempx += dx
if not 0 <= tempy < width or not 0 <= tempx < length:
return
if arr[tempy][tempx]:
if cnt == 1 or arr[tempy][tempx] == cur:
return
graph.add((cur, …
```
> [Solved] : [BOJ] 17472 다리 만들기 2 문제 해결

- minsun/SWEA/23795/sol.py
- 내용 : [문제 링크](https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AZU7flp6n8XHBIRK)
```python
dxy = [[0, -1], [0, 1], [-1, 0], [1, 0]]
matrix = [list(map(int, input().split())) for _ in range(N)]
cnt = 0
if matrix[i][j] == 2:
for k in range(N):
nx = i + dx * k
ny = j + dy * k
if 0 <= nx < N and 0 <= ny < N and matrix[nx][ny] != 1:
matrix[nx][ny] = 3
else:
break
if matrix[i][j] == 0:
cnt += 1
print(f"#{tc}", cnt)
```
- 프린트함
> [Solve] : [SWEA] 23795 - 우주 괴물 문제 해결

- minsun/SWEA/22654/sol.py
[문제 링크](https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AZIx55YKpg0DFAQP)
```python
"""
1. R A L 구분해야함
2. R 인 경우 오른쪽 90도 회전
3. A 장애물 있으면 안 감
4. L 왼쪽으로 90도 회전
이거 왼 오를 어떻게 구별할것인지?
5. 이것만 해결하면 그냥 델타탐색 하면 됨
"""
dxy = [(-1, 0), (0, 1), (1, 0), (0, -1)]
matrix = [list(map(str, input().strip())) for _ in range(N)]
Q = int(input()) # 조종을 한 횟수
result = []
for _ in range(Q):
start_x = start_y = 0
dir = 0
if matrix[i][j] == 'X':  # 처음위치
start_x, start_y = i, j
C, command = map(str, input().split())
for r_c in command:
if r_c == "R":
dir = (dir + 1) % 4
elif r_c == "L":
dir = (dir - 1) % 4
else:
dx, dy = dxy[dir]
nx = start_x + dx
ny = start_y + dy
if 0 <= nx < N and 0 …
```
> [Solve] : [SWEA] 22654 - 차윤이의 RC카 문제 해결

- minsun/SWEA/22407/sol.py
D2
- 내용 : [문제 링크](https://swexpertacademy.com/main/code/userProblem/userProblemDetail.do?contestProbId=AZHVeb9KW6IDFAQP)
```python
import sys
def drawing(x1, y1, x2, y2):
for i in range(x1, x2+1):
for j in range(y1, y2+1):
white_board[i][j] += 1
N = 10
white_board = [[0]*N for _ in range(N)]
row = col = 0
r_r1, r_c1, r_r2, r_c2 = map(int, input().split()) # 빨간색
b_r1, b_c1, b_r2, b_c2 = map(int, input().split()) # 파란색
drawing(r_r1, r_c1, r_r2, r_c2)
drawing(b_r1, b_c1, b_r2, b_c2)
for k in range(N):
row = 0
for l in range(N):
if white_board[k][l] == 2:
row += 1
if row > 0:
break
for m in range(N):
col = 0
for n in range(N):
if white_board[n][m] == 2:
col += 1
if col > 0:
break
print(f"#{tc}", row, col)
```
- 마지막에 …
> [Solve] : [SWEA] 22407 - 색칠하기 3 문제 해결

- minsun/BOJ/1652/sol.py
[BOJ] 1652:
- 문제 유형 : 구현
- 문제 난이도 : 백준 실버 5
- 시간 : 36ms
- 내용 : [문제 링크](https://www.acmicpc.net/problem/1652)
```python
import sys
def garo():
result = 0
cnt = 0
if matrix[i][j] == '.':
cnt += 1
else:
if cnt >= 2:
result += 1
cnt = 0
if cnt >= 2:
result += 1
return result
def sero():
result = 0
cnt = 0
if matrix[i][j] == '.':
cnt += 1
else:
if cnt >= 2:
result += 1
cnt = 0
if cnt >= 2:
result += 1
return result
matrix = [list(map(str, input().strip())) for _ in range(N)]
garo_result = garo()
sero_result = sero()
print(garo_result, sero_result)
```
- 누울자리를찾아라 ~~~
> [Solve] : [BOJ] 1652 - 누울 자리를 찾아라 문제 해결

- Minwoo/SWEA/22683/sol.py
- 제목 : [해결 여부] : [문제 사이트] 문제 번호 - 메세지
- 아래 예시 참고
```python
def bfs():
global data, N, sx, sy, K, result
dx = [-1, 0, 1, 0]
queue = deque([(sx, sy, K, 0, 0)])
visited = [[[[False] * N for _ in range(N)] for __ in range(K+1)] for ___ in range(4)]
visited[0][K][sx][sy] = True
def is_valid(ix, iy, kk, dir, count):
nonlocal queue, visited, dx, dy
right = (dir + 1) % 4
if not visited[right][kk][ix][iy]:
queue.append((ix, iy, kk, right, count))
visited[right][kk][ix][iy] = True
left = (dir - 1) % 4
if not visited[left][kk][ix][iy]:
queue.append((ix, iy, kk, left, count))
visited[left][kk][ix][iy] = True
while queue:
x, y, k, d, cnt = queue.popleft()
if data[x][y] == 'Y':
result = cnt
return
cnt += 1
nx, ny = x + …
```
> [Solve] : [SWEA] 22683 나무 베기 - 문제 해결

- kimchaejun/BOJ/11723/sol.py
```python
import sys
N = int(sys.stdin.readline())
S, res = 0, []
order = sys.stdin.readline().split()
if order[0] == 'all':
S = (1 << 20)-1
elif order[0] == 'empty':
S = 0
else:
n = int(order[1])-1
if order[0] == 'add':
S |= (1 << n)
if order[0] == 'remove':
S &= ~(1 << n)
if order[0] == 'check':
sys.stdout.write('1\n' if S & (1 << n) else '0\n')
if order[0] == 'toggle':
S ^= (1 << n)
```
- 명령어가 입력되었을 때마다 정해진 동작이 수행되어야하며, 출력은 check가 실행될 때만 진행한다.
- add:값 추가 | remove:값 제거 | check:유무 확인 | toggle:있으면 제거, 없으면 추가 | all:전부 추가 | empty:전부 제거
- 처음엔 리스트로 풀었는데, 문제 태그에 비트마스크가 적혀있는 것을 보고 비트 연산으로 만들었습니다.
- 그런데 계속 메모리 초과, 시간 초과가 뜨길래 입출력을 sys 모듈을 통해 직접 제어했더니 통과되었습니다.
- O(N) (비트 연산은 O(1)이기 때문에!)
> [Solve] : [BOJ] 11723-집합문제해결

- JYJ/BOJ/2567/sol.py
[Solve] : 2567 색종이 - 2 문제해결
https://www.acmicpc.net/problem/2567
```python
'''
둘레를 어케 구하는데
델타? 돌려서 0찾으면 제일 바깥이라는 거니까
+1
'''
dxy = [[0, 1], [1, 0], [-1, 0], [0, -1]]
arr = [[0] * 101 for _ in range(101)]
cnt = 0
for _ in range(n):
x, y = map(int,input().split())
for i in range(x, x + 10):
for j in range(y, y + 10):
arr[i][j] = 1
for i in range(101):
for j in range(101):
if arr[i][j] == 1:
ni = i + dx
nj = j + dy
if not(0 <= ni < 101 and 0 <= nj < 101): continue
if arr[ni][nj] == 1: continue
if arr[ni][nj] == 0:
cnt += 1
print(cnt)
```
- 넓이가 아닌 둘레를 구하라 해서 뇌정지 왓었는데
그냥 1인 부분에서 델타 돌려서 0을 찾으면 제일 바깥에 위치한다는 거니까
더해줬습니다
> [Solve] : 2567 색종이 - 2 문제해결

- JYJ/BOJ/12891/sol.py
[Solve] : [BOJ] 12891 DNA 비밀번호 - 문제 해결
https://www.acmicpc.net/problem/12891
```python
'''
배열에서 p개씩 슬라이싱
DNA 리스트에 있는지 없는지 검사
주어진 문자의 최소 개수가 맞는지 검사
조건에 맞는 사용할 수 있는 비밀번호의 개수 출력
'''
#
#
import sys
s, p = map(int, input().split())
arr = list(input().strip())
A_target, C_target, G_target, T_target = map(int, input().split())
a_count = 0
c_count = 0
g_count = 0
t_count = 0
for i in range(p):
if arr[i] == 'A':
a_count += 1
elif arr[i] == 'C':
c_count += 1
elif arr[i] == 'G':
g_count += 1
elif arr[i] == 'T':
t_count += 1
cnt = 0
if a_count >= A_target and c_count >= C_target and g_count >= G_target and t_count >= T_target:
cnt += 1
for i in range(p, s):
out_char = arr[i - p]
if out_char == 'A':
a_count -= 1
elif out_char == 'C':
c_count -= …
```
> [Solve] : [BOJ] 12891 DNA 비밀번호 - 문제 해결

- comet/SWEA/3950/sol.py
```python
def r_operation(left, right, string):
string = list(string)
string[left:right + 1] = string[left:right + 1][::-1]
for i in range(left, right + 1):
if string[i] == '(':
string[i] = ')'
elif string[i] == ')':
string[i] = '('
return ''.join(string)
def flip(string):
global flip_cnt, result
min_value = 0
pos = -1
total = 0
for i in range(len(string)):
if string[i] == '(':
total += 1
elif string[i] == ')':
total -= 1
if total < min_value:
min_value = total
pos = i
if pos != -1:
flip_cnt += 1
result.append((0, pos))
string = r_operation(0, pos, string)
return string
def solve(string):
global flip_cnt, result, sub_sum_arr
n = len(string)
if n % 2 == 1:
flip_cnt = -1
return
string = flip(string)
sub_sum_arr = []
total = 0
for ch in string:
if ch == '(':
total += 1
elif ch == ')':
total …
```
> [Solved] : SWEA/3950 괄호 문제풀이

- kimchaejun/BOJ/2630/sol.py
```python
paper = [list(map(int, input().split())) for _ in range(N)]
blue, white = 0, 0
def binary_search(x, y, size):
global blue, white
check = sum([paper[i][j] for j in range(x, x+size) for i in range(y, y+size)])
if check == 0:
white += 1
elif check == (size**2):
blue += 1
else:
half = size // 2
binary_search(x, y, half)
binary_search(x+half, y, half)
binary_search(x, y+half, half)
binary_search(x+half, y+half, half)
binary_search(0, 0, N)
print(white)
print(blue)
```
```python
paper = [list(map(int, input().split())) for _ in range(N)]
blue, white = 0, 0
def binary_search(x, y, size):
global blue, white
std = paper[y][x]
check = True
for i in range(y, y+size):
for j in range(x, x+size):
if std != paper[i][j]:
check = False
break
if not check:
break …
```
> [Solve] : [BOJ] 2630 - 색종이 만들기 문제 해결

- JYJ/BOJ/14889/sol.py
[Solve] : [BOJ] 14889 스타트와 링크 - 문제 해결
https://www.acmicpc.net/problem/14889
```python
from itertools import combinations
'''
'''
arr = [list(map(int,input().split())) for _ in range(n)]
min_num = 999999999999
people = [i for i in range(n)]
for i in combinations(people, n//2):
a = list(set(people) - set(i)) # team 1 == i, team 2 == a
start = 0
link = 0
for j in range(n//2):
for k in range(n//2):
if j == k: continue
start += arr[i[j]][i[k]]
link += arr[a[j]][a[k]]
min_num = min(min_num, abs(start - link))
if min_num == 0: # 최소가 0이면 계산할 필요 없음
break
print(min_num)
```
- 팀을 2개로 나눠 비교합니다. combinations 사용해서 완전탐색 했고, 문제 유형에 백트래킹 있길래 가지치기좀 했습니다.
- 그래도 7000ms 정도 나오던데 combinations 안쓰는 방법이 있다면 구독과 좋아요
> [Solve] : [BOJ] 14889 스타트와 링크 - 문제 해결

- kimchaejun/BOJ/1449/sol.py
* 난이도 : 실버 3
* 알고리즘 분류 : 그리디, 정렬
```python
N, L = map(int, input().split())
repair_point = sorted(list(map(int, input().split())))
i, res = 0, 0
while i < N:
std = repair_point[i]
res += 1
while i < N and repair_point[i] < std + L:
i += 1
print(res)
```
- 입력을 정렬하여 받아온다.
- while loop를 통해 시작값 + L로 최대 범위를 잡고, 가능하면 i 증가, 불가능해지면 res를 증가시키고 std 값을 변경한다.
- res값을 출력한다.
- 최선 평균 최악 모두 O(N log N)
> [Solve] : [BOJ] 1449 - 수리공 항승 문제 해결

- minsun/BOJ/10163/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/10163)
```python
length = 1001
white = [[0] * length for _ in range(length)]
for z in range(1, N+1):
x1, y1, x2, y2 = map(int, input().split())
for i in range(x1, x1+x2):
for j in range(y1, y1+y2):
white[i][j] = z
for n in range(1, N+1):
cnt = 0
for w in white:
for y in w:
if y == n:
cnt += 1
print(cnt)
```
- 아 배고파 ..
> [Solve] : [BOJ] 10163 - 색종이 문제해결

- JYJ/BOJ/7576/sol.py
[Solve] : [BOJ] 7576 토마토 - 문제 해결
https://www.acmicpc.net/problem/7576
```python
import sys
'''
'''
dxy = [[0, 1], [1, 0], [-1, 0], [0, -1]]
def bfs():
queue = deque()
depth = 0
for i in range(n): # 토마토 한개인줄 알았는데 아님;;
for j in range(m):
if arr[i][j] == 1:
queue.append((i, j, 0))
while queue:
i, j, depth = queue.popleft()
ni = i + dx
nj = j + dy
if not(0 <= ni < n and 0 <= nj < m) or arr[ni][nj] == -1 or arr[ni][nj] == 1: continue
arr[ni][nj] = 1
queue.append((ni, nj, depth + 1))
return depth
m, n = map(int,input().split())
arr = [list(map(int,input().split())) for _ in range(n)]
result = bfs()
for i in range(n): # 익지 않은 토마토(0)이 있다면 -1 출력
for j in range(m):
if arr[i][j] == 0:
result = …
```
> [Solve] : [BOJ] 7576 토마토 - 문제 해결

- minsun/BOJ/16918/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/16918)
```python
import sys
"""
RxC 직사각형 격자판 위
3초가 지난 후 폭발
폭탄이 폭발한 이후에는 폭탄이 있던 칸이 파괴 빈칸이 되며, 인접한 네 칸도 파괴
"""
def boom():
result_map = [[0]*C for _ in range(R)]
for i in range(R):
for j in range(C):
if boom_map[i][j] == 'O':
result_map[i][j] = '.'
nx = i + dx
ny = j + dy
if 0 <= nx < R and 0 <= ny < C:
result_map[nx][ny] = '.'
return result_map
dxy = [[1,0], [-1, 0], [0, 1], [0, -1]]
R,C,N = map(int, input().split())
boom_map = [list(input().strip()) for _ in range(R)]
result_map = [[0]*C for _ in range(R)]
time = 1
if N % 2 != 0:
N -= 1
while N > 0:
result = boom()
N -= 1
if N == 0:
break
for i in result:
print(*i, sep='')
else:
for i in result_map:
print(*i, sep='')
```
- 테케 3이 안 맞음 조금만 …
> [Fail] : [BOJ] 16918 봄버맨 - 해결 중

- minsun/BOJ/3085/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/3085)
백준 실버2 
```python
def check_candy(candy):
max_count = 0
count = 1
for j in range(N-1):
if candy[i][j] == candy[i][j+1]:
count += 1
if count > max_count:
max_count = count
else:
count = 1
return max_count
def check_candy2(candy):
max_count = 0
count = 1
for i in range(N-1):
if candy[i][j] == candy[i+1][j]:
count += 1
if count > max_count:
max_count = count
else:
count = 1
return max_count
candies = [list(map(str, input().strip())) for _ in range(N)]
result1 = 0
result2 = 0
result = 0
if i + 1 < N:
if candies[i][j] != candies[i+1][j]:
candies[i][j], candies[i+1][j] = candies[i+1][j], candies[i][j]
result1 = check_candy(candies)
result2 = …
```
> [Solve] : [BOJ] 3085 - 사탕게임 문제해결

- kimchaejun/BOJ/2108/sol.py
목차 | 정보
:--: | :--:
난이도 | 실버 2
알고리즘 분류 | 수학 / 구현 / 정렬
링크 | [[BOJ] 2108 - 통계학](https://www.acmicpc.net/problem/2108)
```python
import sys
from collections import Counter
data_in = sys.stdin.readline
N = int(data_in())
res = [0] * 4
nums = sorted(int(data_in()) for _ in range(N))
res[0] = round(sum(nums) / N)
res[1] = nums[N//2]
nums_cnt = Counter(nums).most_common()
nums_most_arr = [v for v, c in nums_cnt if c == nums_cnt[0][1]]
nums_most_arr.sort()
res[2] = nums_most_arr[1] if len(nums_most_arr) > 1 else nums_most_arr[0]
res[3] = max(nums) - min(nums)
for r in res:
print(r)
```
- 사실 가장 문제였던건 최빈값이었다.
- 구현은 해냈지만, 시간 초과가 뜨길래 열심히 구글링했고, 내장 함수 중에 Counter라는 클래스를 찾을 수 있었다.
- Counter :  문자열 또는 리스트 내에 있는 자료와 그 자료의 개수를 딕셔너리화 해준다.
- 찾아보니 해시로 접근하는 친구라서 훨씬 빠르다고 합니다.
- 아무튼 Counter를 이용하여 간단하게 구현했습니다. …
> [Solve] : [BOJ] 2108 - 통계학 문제해결

- comet/BOJ/2011/sol.py
문제 난이도 : 골드 5
문제 유형 : DP
[암호코](https://www.acmicpc.net/problem/2011)
```python
def find(code):
if code[1] == 0:
return 0
dp = [0] * (len(code))
dp[0] = 1
dp[1] = 1
for i in range(2, len(code)):
if code[i] == code[i - 1] == 0:
return 0
if code[i]:
dp[i] += dp[i - 1]
if code[i - 1] and code[i - 1] * 10 + code[i] <= 26:
dp[i] += dp[i - 2]
dp[i] %= 1000000
return dp[-1]
code = [0] + list(map(int, list(input().strip())))
print(find(code))
```
- 알파벳 > 숫자가 1~ 26이니 첫 숫자가 0이면 해독 불가능. 
- 혹은 두 숫자가 연속으로 0 0 이여도 해독 불가능
- 만약 현재 값이 0이 아니면 A ~ I 로 해독 가능하니 n - 1 번째의 경우의 수를 그대로 가져올 수 있음.
- 만약 n - 1의 값이 0이 아니면 두 글자로 만들어 j ~ z 의 알파벳으로 만들 수 있으니 두글자로 이어붙인 값이 26 이하면 n - 2 번째의 경우의 수를 그대로 가져올 수 있음. 
- 이것을 반복
> [Solved] : BOJ/2011 암호코드 문제해결

- kimchaejun/BOJ/14472/sol.py
목차 | 정보
:--: | :--: 
난이도 | 실버 5
알고리즘 분류 | 구현 / 문자열 / 브루트포스 알고리즘
링크 | [[BOJ] 14472 - Refreshment Area](https://www.acmicpc.net/problem/14472)
출력 | ```.```이 ```L```만큼 있는 경우의 수 (겹치는 부분 제외, 가로 세로 모두 포함)
특징 | 문제가 일본어로 되어있습니다.
```python
def check(x, y, r):
global res
dxy = [[0, 1], [1, 0], [-1, 0], [0, -1]]
ch = []
cnt = 1
for k in range(1, r):
nx, ny = x + dx * k, y + dy * k
if 0 <= nx < N and 0 <= ny < M and field[nx][ny] == '.':
cnt += 1
ch.append(cnt)
res += ch.count(L)
N, M, L = map(int, input().split())
field = [input() for _ in range(N)]
visited = [[[False]*M for _ in range(N)] for _ in range(4)]
res = 0
for j in range(M):
if field[i][j] == '#':
continue
check(i, j, L)
print(res//2)
```
```py
def check(x, y, r):
global res
dxy = [[0, 1], [1, 0]]
ch = …
```
> [Solve] : [BOJ] 14472 - Refreshment Area 문제 해결

- seunghoon/BOJ/2660/sol.py
[BOJ] : 2660
- 사용 알고리즘 : BFS
- 난이도 : 백준 골드 5
- 시간 : 60ms
```python
def bfs(node):
q = deque([(node, 0)])
visited = [0] * (n+1)
visited[node] = 1
while q:
student, depth = q.popleft()
for friend in nodes[student]:
if visited[friend]:
continue
visited[friend] = 1
q.append((friend, depth+1))
return depth
nodes = [[] for _ in range(n+1)]
while 1:
a,b = map(int,input().split())
if a == -1 and b == -1:
break
nodes[a].append(b)
nodes[b].append(a)
min_depth = 100000000
res = []
for i in range(1,n+1):
depth = bfs(i)
if min_depth > depth:
min_depth = depth
res = [i]
elif min_depth == depth:
res.append(i)
print(min_depth, len(res))
print(' '.join(map(str, res)))
```
- 인접한 node 연결처리
- bfs를 통해 순회하며 이때 depth를 넘겨줌
- bfs가 끝나면 : 더이상 탐색할 인접 데이터가 없을때 ( 친구를 다 …
> [SOLVE] : BOJ 2660 문제풀이

- comet/BOJ/14499/sol.py
문제 난이도 : 골드 4
문제 유형 : 시뮬레이션
```python
def roll(dice, direc):
if direc == 1:
dice[1], dice[3], dice[4], dice[6] = dice[4], dice[1], dice[6], dice[3]
elif direc == 2:
dice[1], dice[3], dice[4], dice[6] = dice[3], dice[6], dice[1], dice[4]
elif direc == 3:
dice[1], dice[2], dice[5], dice[6] = dice[5], dice[1], dice[6], dice[2]
elif direc == 4:
dice[1], dice[2], dice[5], dice[6] = dice[2], dice[6], dice[1], dice[5]
return
width, length, dice_y, dice_x, command_num = map(int, input().split())
arr = [list(map(int, input().split())) for _ in range(width)]
commands = list(map(int, input().split()))
dice = [0] * 7
dy = [0, 0, 0, -1, 1]
dx = [0, 1, -1, 0, 0]
for command in commands:
if not 0 <= dice_y + dy[command] < width or not 0 <= dice_x + dx[command] < length:
continue
roll(dice, command) …
```
> [Solved] : BOJ/14499 주사위 굴리기 문제 해결

- comet/BOJ/14500/sol.py
난이도 : 골드 4
문제 유형 : 구현, 브루트포스
```python
def dfs(y, x, val, cnt):
global result, width, length, visited
if cnt == 4:
result = max(result, val)
return
for dy, dx in [(1, 0), (0, 1), (-1, 0), (0, -1)]:
tempy = y + dy
tempx = x + dx
if 0 <= tempy < width and 0 <= tempx < length and not visited[tempy][tempx]:
visited[tempy][tempx] = 1
dfs(tempy, tempx, val + arr[tempy][tempx], cnt + 1)
visited[tempy][tempx] = 0
def find(y, x):
global arr, length, width
val = []
if y != 0:
val.append(arr[y - 1][x])
if y != width - 1:
val.append(arr[y + 1][x])
if x != 0:
val.append(arr[y][x - 1])
if x != length - 1:
val.append(arr[y][x + 1])
if len(val) <= 2:
return None
elif len(val) == 3:
return sum(val) + arr[y][x]
else:
return sum(val) - min(val) + arr[y][x]
width, length = map(int, input().split())
arr = …
```
> [Solved] : BOJ/14500 테트로미노

- kimchaejun/BOJ/2635/sol.py
목차 | 정보
:--: | :--:
난이도 | 실버 5
알고리즘 분류 | 수학 / 브루트포스 알고리즘
링크 | [[BOJ] 2635 - 수 이어가기](https://www.acmicpc.net/problem/2635)
```python
def fibonacci(n, n2):
global res, cnt
tmp_fib = [n, n2]
idx = 2
while True:
tmp = tmp_fib[idx-2] - tmp_fib[idx-1]
if tmp < 0:
fib_len = len(tmp_fib)
if fib_len > cnt:
res.clear()
cnt = fib_len
res.append(tmp_fib)
break
tmp_fib += [tmp]
idx += 1
res, cnt = [], 0
for i in range(N, -1, -1):
fibonacci(N, i)
print(cnt)
print(' '.join(map(str, res[0])))
```
- N을 기준으로 감소하는 피보나치 수열을 만들어서 그 중 가장 큰 길이를 가지는 값을 출력한다.
- 첫번째 줄은 가장 긴 수열의 길이이고, 두번째에는 만들어진 수열 중 하나를 출력한다. 
- (전 그냥 제일 먼저 나온 값으로 출력했습니다.)  
케이스 | 시간 복잡도
:--: | :--: 
최선(Best) | O(N)
평균(Avg) | O(N * k)
최악(Worst) | O(N²)
> [Solve] : [BOJ] 2635 - 수 이어가기 문제 해결

- JYJ/BOJ/2493/sol.py
[Solve] : [BOJ] 2493 탑 - 문제 해결
https://www.acmicpc.net/problem/2493
```python
import sys
'''
'''
arr = list(map(int,input().split()))
result = [0] * n
stack = []
while stack and stack[-1][0] < arr[i]:
stack.pop()  # 자신보다 작은 건 의미 없음
if stack:
result[i] = stack[-1][1]  # 가장 가까운 큰 수의 인덱스
else:
result[i] = 0  # 왼쪽에 자신보다 큰 수가 없음
stack.append((arr[i], i + 1))  # 현재 값과 위치 저장
print(*result)
```
- while 조건으로 한번 거르고 스택에 값이 있다면 비교하면 끝
> [Solve] : [BOJ] 2493 탑 - 문제 해결

- jinhyeon/BOJ/2116/sol.py
[🐴 < 🐵](https://www.acmicpc.net/problem/1600)
```python
k = int(input().rstrip())
w, h = map(int, input().rstrip().split())
arr = [list(map(int, input().rstrip().split())) for _ in range(h)]
visited = [[[0] * w for _ in range(h)] for _ in range(k + 1)]
dxl = [0, 1, 0, -1]
dyl = [1, 0, -1, 0]
dxl_j = [-2, -1, 1, 2,  2,  1, -1, -2]
dyl_j = [1,  2,  2, 1, -1, -2, -2, -1]
def bfs(x, y, jump): #jump = 점프 횟수
q = deque()
q.append((x, y, jump))
visited[jump][x][y] = 1
while q:
x, y, jump = q.popleft()
if x == h-1 and y == w-1:
return visited[jump][x][y] - 1
if jump:
for dx, dy in zip(dxl_j, dyl_j):
nx = x + dx
ny = y + dy
if 0 <= nx < h and 0 <= ny < w and not arr[nx][ny] and not visited[jump-1][nx][ny]:
q.append((nx , ny, jump-1))
visited[jump-1][nx][ny] = …
```
> [Solve]:  [BOJ] 1600 - 말이 되고픈 원숭이 문제 해결

- JYJ/BOJ/2635/sol.py
[Solve] : [BOJ] 2635 수 이어가기 - 문제 해결
https://www.acmicpc.net/problem/2635
```python
import sys
sys.stdin = open('input.txt', 'r')
#########################################
def minus(num1):
max_cnt = 0
my_list1 = []
for i in range(1, num1 + 1):
hund = num1
numi = i
cnt = 2
my_list = [num1]
my_list.append(i)
while True:
numbers = hund - numi # i에서 넘버스를 빼야함 그러고 나온 값을 또 저장해야 함
hund = numi
numi = numbers  # 저장한 값을 넘버스에서 빼줘야 함
if numbers < 0:
break
my_list.append(numbers) # 출력을 하기 위해 리스트에 100하고 62도 추가해야 함 중복 x
cnt += 1
if max_cnt < cnt:
max_cnt = cnt
my_list1 = my_list.copy()
return max_cnt, my_list1
re, sult = minus(N)
print(re)
print(*sult)
```
- 예전에 풀었던건데 실패인거 고쳤습니다
두 번째 정수를 선택해야 하는데 완전 탐색 돌려서
두 번째 정수 고르고 연산합니다
그리고 가장 많은 횟수를 연산했다면 그 연산한 리스트도 같이 …
> [Solve] : [BOJ] 2635 수 이어가기 - 문제 해결

- Minwoo/BOJ/2589/sol.py
- 제목 : [Solve] : [BOJ] 2589 보물섬 - 문제 해결
- 난이도 : Gold 5
- 분류 : 너비 우선 탐색
```python
dxy = [(1, 0), (0, 1), (-1, 0), (0, -1)]
def bfs(ix, iy):
global grid, R, C, max_value
visited = [[False] * C for _ in range(R)]
queue = deque([(ix, iy, 0)])
visited[ix][iy] = True
while queue:
x, y, cnt = queue.popleft()
max_value = max(max_value, cnt)
cnt += 1
if nx < 0 or nx >= R or ny < 0 or ny >= C:
continue
if visited[nx][ny] or grid[nx][ny] == 'W': continue
queue.append((nx, ny, cnt))
visited[nx][ny] = True
R, C = map(int, input().split())
grid = [list(input().strip()) for _ in range(R)]
max_value = 0
for i in range(R):
for j in range(C):
if grid[i][j] == 'L':
bfs(i, j)
print(max_value)
```
- 프린트함
> [Solve] : [BOJ] 2589 보물섬 - 문제 해결

- ImSeoHyun/BOJ/10773/sol.py
- ImSeoHyun/BOJ/2669/sol.py
[Solve][Boj ]2669 직사각형 네개의 합집합의 면적 구하기
[직사각형 네개의 합집합의 면적 구하기](https://www.acmicpc.net/problem/2669)
```python
arr = [list(map(int , input().split())) for _ in range(4)]
area = [[0] * 101 for _ in range(101)]
for i in range(4):
x1, y1, x2, y2 = arr[i]
for x in range(x1, x2):
for y in range(y1, y2):
area[x][y] = 1
result = 0
for k in range(101):
for j in range(101):
if area[k][j] == 1:
result += 1
print(result)
```
공간을 만들어 x의 좌표와 y좌표를 1로 채워 직사각형 안을 채운다. 
순회하며 개수를 세고 프린트 한다.
> [Solve]:[Boj ]2669 직사각형 네개의 

- Minwoo/BOJ/1331/sol.py
- 제목 : [Solve] : [BOJ] 1331 나이트 투어 - 문제 해결
- 난이도 : Silver 4
- 분류 : 구현 / 시뮬레이션
```python
dxy = [(-1, -2), (-2, -1), (-2, 1), (-1, 2), (1, 2), (2, 1), (2, -1), (1, -2)]
def brute_force():
global coordinate, K, N
visited = set()
visited.add(coordinate[0])
bx, by = coordinate[0]
for x, y in coordinate[1::]:
if (x, y) in visited:
return 'Invalid'
if (abs(bx-x), abs(by-y)) not in [(1, 2), (2, 1)]:
return 'Invalid'
visited.add((x, y))
bx, by = x, y
if nx < 0 or nx >= N or ny < 0 or ny >= N:
continue
if (nx, ny) == coordinate[0]:
return 'Valid'
return 'Invalid'
N = 6
K = 36
coordinate = []
dicA = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5}
for _ in range(K):
a, b = list(input().strip())
coordinate.append((dicA[a], …
```
> [Solve] : [BOJ] 1331 나이트 투어 - 문제 해결

- minsun/BOJ/1913/sol.py
[Solve] : [BOJ] 1913 - 달팽이 문제해결 🐌
- 내용 : [문제 링크 ](https://www.acmicpc.net/problem/1913)
```python
dx = [1, 0, -1, 0]
find_N = int(input())
matrix = [[0]*N for _ in range(N)]
i, j, cnt, dr = 0, 0, N*N, 0
matrix[i][j] = cnt
cnt -= 1
while True:
nx = i + dx[dr]
ny = j + dy[dr]
if 0 <= nx < N and 0 <= ny < N and matrix[nx][ny] == 0:
i, j = nx, ny
matrix[i][j] = cnt
cnt -= 1
else:
dr = (dr+1)%4
if cnt == 0:
break
if matrix[i][j] == find_N:
x, y = i + 1, j + 1
for l in matrix:
print(*l)
print(x, y)
```
- cnt == 1 로 멈추니까 0이 나왓네요 마지막값이 ..
> [Solve] : [BOJ] 1913 - 달팽이 문제해결 🐌

- kimchaejun/BOJ/2116/sol.py
목차 | 정보
:--: | :--:
난이도 | 골드 5
알고리즘 분류 | 구현 / 브루트포스 알고리즘
링크 | [[BOJ] 2116 - 주사위 쌓기](https://www.acmicpc.net/problem/2116)
```python
top_and_bottom = [[0, 1, 1, 1, 1, 0], [1, 0, 1, 0, 1, 1], [1, 1, 0, 1, 0, 1]]
dices = [list(map(int, input().split())) for _ in range(N)]
res = float('-inf')
for i in range(6):
sides = 0
std = dices[0][i]
if i > 2:
b_ind = 0 if i == 5 else (1 if i == 3 else 2)
else:
b_ind = i
sides += max([dices[0][k] for k in range(6) if top_and_bottom[b_ind][k]])
for j in range(1, N):
ind = dices[j].index(std)
if ind > 2:
d_ind = 0 if ind == 5 else (1 if ind == 3 else 2)
std = dices[j][d_ind]
else:
d_ind = ind
std = dices[j][5 if ind == 0 else (3 if ind == 1 else 4)]
sides += max([dices[j][k] for k in range(6) if top_and_bottom[d_ind][k]])
res = max(res, …
```
> [Solve] : [BOJ] 2116 - 주사위 쌓기 문제 해결

- Minwoo/BOJ/2567/sol.py
- 난이도 : Silver 4
- 분류 : 구현
```python
def color(x, y):
global M, paper
for i in range(y, y+M):
for j in range(x, x+M):
paper[i][j] = 1
def check():
global paper, K
dxy = (1, 0), (0, 1), (-1, 0), (0, -1)
cnt = 0
for i in range(K):
for j in range(K):
if paper[i][j] == 1:
for di, dj in dxy:
ni, nj = i + di, j + dj
if not(0 <= ni < K and 0 <= nj < K):
continue
if paper[ni][nj] == 0:
cnt += 1
return cnt
K = 102
M = 10
paper = [[0] * K for _ in range(K)]
r, c = map(int, input().split())
color(r, c)
print(check())
```
- 색종이를 칠한 부분(1)에서 상하좌우 탐색했을 때 만난 0 만큼이 테두리입니다.
> [Solve] : [BOJ] 2567 색종이-2

- JYJ/BOJ/2116/sol.py
[Solve] : [BOJ] 2116 주사위 쌓기 - 문제 해결
https://www.acmicpc.net/problem/2116
```python
'''
0 : 5
1 : 4
2 : 3
'''
dice = [list(map(int,input().split())) for _ in range(n)]
updown = {0 : 5, 1 : 3, 2 : 4, 5 : 0, 4 : 2, 3 : 1}
max_cnt = 0
for i in range(6):
cnt = 0
a = dice[0][updown[i]]
for j in range(n):
max_num = 0
idx = 0
for k in range(6):
if a == dice[j][k]:
idx = k
a = dice[j][updown[k]]
break
for l in range(6):
if l == idx or l == updown[idx]:
continue
if max_num == 6:
break
max_num = max(max_num, dice[j][l])
cnt += max_num
if max_cnt < cnt:
max_cnt = cnt
print(max_cnt)
```
- 딕셔너리로 아랫면이 선택되었을 때 더할 수 없는 윗면의 인덱스 정의
제외할 값의 인덱스를 찾아 놓고 idx와 idx의 반댓면일 경우 continue
max_num이 6일 경우 이미 최대이기 때문에 break
남은 인덱스 중 가장 큰 값을 더한다(위, 아랫면만 빼면 돌려도 상관 없기 때문)
그 후 …
> [Solve] : [BOJ] 2116 주사위 쌓기 - 문제 해결

- jinhyeon/BOJ/2023/sol.py
[BOJ] 2023:
- 문제유형: 백트래킹
- 문제난이도: 백준 골드 5
- 시간복잡도: 3028ms
- 공간복잡도: 109mb
[2️⃣ 3️⃣ 5️⃣ 7️⃣ ](https://www.acmicpc.net/problem/2023)
```python
def is_prime_num(num):
flag = True
if num == 1 and num == 0:
flag = False
for i in range(2, num):
if not num % i:
flag = False
break
return flag
def is_beautiful_prime_num(num):
if not is_prime_num(num):
return
if len(str(num)) == n:
result.append(num)
return
for i in range(10):
is_beautiful_prime_num(num * 10 + i)
result = []
for i in range(2, 10):
is_beautiful_prime_num(i)
print('\n'.join(map(str, result)))
```
- 간단한 백트래킹 문제입니다
> [Solve]: [BOJ] 신기한 소수 문제 해결

- minsun/BOJ/14696/sol.py
- minsun/BOJ/2477/sol.py
- minsun/BOJ/2605/sol.py
딱지놀이 
참외밭
줄세우기 
끝이다 !!! 
떨어지면 즙짤거임 미리 준비한다
> [Solve]:[BOJ] 14696 2477 2605 문제해결

- Minwoo/BOJ/11403/sol.py
- 난이도 : Silver 5
- 분류 : 정렬
```python
import sys
def bfs(vtx):
global graph, V
visited = [0] * V
queue = deque([vtx])
while queue:
vtx = queue.popleft()
for adj in range(V):
if graph[vtx][adj] > 0:
if visited[adj]: continue
queue.append(adj)
visited[adj] = 1
return visited
V = int(input())
graph = [list(map(int, input().split())) for _ in range(V)]
for i in range(V):
print(' '.join(map(str, bfs(i))))
```
- 모든 정점에서 이동 가능한 정점들의 방문처리를 반환해서 join -> 출력했습니다.
> [Solve] : [BOJ] 11403 경로 찾기 - 문제 해결

- jinhyeon/BOJ/16236/sol.py
[BOJ] 16236:
- 문제유형: 시뮬레이션, 구현, bfs
- 문제난이도: 백준 골드 3
- 시간복잡도: 136ms
- 공간복잡도: 114mb
[🦈](https://www.youtube.com/watch?v=761ae_KDg_Q)
```python
arr = [list(map(int, input().split())) for _ in range(n)]
dxl = [-1, 0, 0, 1] #상 좌 우 하
dyl = [0, -1, 1, 0] #같은 거리의 물고기라도 먼저 먹는 우선순위
s_x, s_y = 0, 0
for j in range(n):
if arr[i][j] == 9:
s_x, s_y = i, j
arr[i][j] = 0
s_size = 2
s_energy = 0
def eat_shark(visited, near_dis):
global s_energy
global s_size
global s_x, s_y
x, y = -1, -1
flag = False
for i in range(n):  #제일 위
for j in range(n):  #제일 왼쪽
if visited[i][j] == near_dis and arr[i][j] and arr[i][j] < s_size:
x, y = i, j
flag = True
break
if flag:
break
s_energy += 1
if s_energy == s_size:
s_energy = 0
s_size += 1
arr[x][y] = 0 …
```
> [Solve]:[BOJ] 아기 상어 문제 해결

- seunghoon/BOJ/14003/sol.py
[BOJ] : 14003
- 사용 알고리즘 : binary_serch(이분탐색), LIS
- 난이도 : 플래 5
- 시간 : 2816ms;;;; pypy + readline사용시 632ms
```python
arr = list(map(int,input().split()))
lis_arr = [arr[0]]
idx_arr = [(arr[0],0)]
def lower_bownd(x):
left = 0
right = len(lis_arr)
while left < right:
mid = (left + right) // 2
if lis_arr[mid] < x:
left = mid + 1
else:
right = mid
return right
for i in range(1, len(arr)):
num = arr[i]
last_num = len(lis_arr)-1
if lis_arr[last_num] < num:
lis_arr.append(num)
idx_arr.append((num, last_num + 1))
else:
idx = lower_bownd(num)
lis_arr[idx] = num
idx_arr.append((num , idx))
j = len(lis_arr)-1
result_arr = []
for i in range(len(idx_arr)-1,-1,-1):
num, idx = idx_arr[i]
if idx == j:
result_arr.append(num)
j -= 1
print(len(result_arr))
print(' '.join(map(str, …
```
> [Solve] : [BOJ] 14003 가장 긴 증가하는 부분 수열 5 문제풀이

- minseo/BOJ/2669/sol.py
- 제목 : [해결 여부] : [문제 사이트] 문제 번호 - 메세지
- 아래 예시 참고
```python
import sys
cnt = 0
visited = [[0]*100 for _ in range(100)]
for tc in range(4):
arr = list(map(int,sys.stdin.readline().split()))
square_x = abs(int(arr[0] - arr[2]))
square_y = abs(int(arr[1] - arr[3]))
for squere_col in range(arr[1],(arr[1]+square_y)):
for squere_row in range(arr[0],(arr[0]+square_x)):
visited[squere_col][squere_row] = 1
for row in range(len(visited)):
for col in range(len(visited)):
if visited[row][col] == 1:
cnt+=1
print(cnt)
```
visted 배열을 만든다. (100*100)
반복문(4번)
시작점(x,y) - 끝점(x,y) = 변의 길이 (a,b)
visited배열에서 시작점 + a 만큼 반복하기
visited 배열에서 끝점 + b 만큼 반복하기
visited 배열 체크하기
visited배열 크기 만큼 반복
visited 배열의 체크된 부분이 있으면 +=1
값 출력
> 입력값을 받는다.
> 정사각형이 차지하는 …
> [solve]2669번 문제해결

- minsun/BOJ/16955/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/16955)
```python
dx = [1, 0, 1, 1]
dy = [0, 1, 1, -1]
def check():
global result
if pan[i][j] == 'X':
for k in range(4):
nx = i
ny = j
count = 1
for _ in range(4):
nx += dx[k]
ny += dy[k]
if 0 <= nx  < N and 0 <= ny < N and pan[nx][ny] == 'X':
count += 1
else:
break
if count == 5:
result = 1
break
N = 10
pan = [list(map(str, input().strip())) for _ in range(N)]
result = 0
if pan[i][j] == '.':
pan[i][j] = 'X'
check()
pan[i][j] = '.'
print(result)
```
> [Solve] : [BOJ] 16955 - 오목, 이길 수 있을까? 문제해결

- JYJ/BOJ/10157/sol.py
[Solve] : [BOJ] 10157 자리배정 - 문제 해결
https://www.acmicpc.net/problem/10157
```python
dxy = [[1, 0], [0, 1], [-1, 0], [0, -1]]
def jari(i, j):
idx = 0
cnt = 1
arr[i][j] = 1
while True:
if cnt == k: # 대기번호 k인 손님 찾기
re, sult = i + 1, j + 1
break
ni = i + dxy[idx][0]
nj = j + dxy[idx][1]
if 0 <= ni < r and 0 <= nj < c and arr[ni][nj] == 0:
arr[ni][nj] = 1
cnt += 1
i, j = ni, nj
else:
idx = (idx + 1) % 4
return re, sult
c, r = map(int,input().split())
k = int(input())
arr = [[0] * c for _ in range(r)]
if c * r < k: # 배열에서 나올 수 있는 수보다 크면 그냥 프린트 0 찍기
print(0)
else:
i, j = jari(0,0)
print(j, i)
```
- 숫자 세고 완전 탐색 돌렸습니다. 하던 도중에 return을 하려고 했는데 while 문이 계속 도는 경우도 있어서
애초에 배열보다 기다리는 순번 k 가 크면 그냥 프린트 찍는거로 조건문 작성하고 풀었습니다
왜 함수에서 리턴 안찍고 브레이크 찍고 리턴했냐?? 수정하다가 완성하고 바꾸기 귀찮아서 그대로 …
> [Solve] : [BOJ] 10157 자리배정 - 문제 해결

- minsun/BOJ/2567/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/2567)
```python
width, height= 101, 101
white =[[0] * width for _ in range(height)]
x,y = map(int,input().split())
for i in range(x,x+10):
for j in range(y,y+10):
white[i][j] = 1
dxy = [[0, -1], [0, 1], [1, 0], [-1, 0]]
cnt = 0
for i in range(width):
for j in range(height):
if white[i][j] == 1:
ni = dx + i
nj = dy + j
if white[ni][nj] == 0: # 네 방향 탐색해서 0 이 있으면 둘레를 구하는 것
cnt +=1
print(cnt)
```
- 술마시고 풀었음 ㅎㅎ
- ㄴ ㅔ방향 탐색해서 0이 있으면 둘레 cnt + 1
> [Solve] : [BOJ] 2567 - 색종이 2 문제해결

- Minwoo/BOJ/10814/sol.py
- 난이도 : Silver 5
- 분류 : 정렬
```python
import sys
temp = [list(input().split()) for _ in range(N)]
arr = [[i, *j] for i, j in  enumerate(temp)]
arr.sort(key=lambda x: (int(x[1]), x[0]))
for i in arr:
print(i[1], i[2])
```
- 쉬운거 푼다고 욕하지 말아주세요... 지하철에서 풀었어요
> [Solve] : [BOJ] 10814 나이순 정렬

- minsun/BOJ/31924/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/31924)
```python
dxs = [0, 0, -1, 1, -1, -1, 1, 1]
dys= [1, -1, 0, 0, -1, 1, -1, 1]
info = [list(map(str, input().strip())) for _ in range(N)]
cnt = 0
for dx, dy in zip(dxs, dys):
word = ''
for k in range(5):
nx = i + dx * k
ny = j + dy * k
if 0 <= nx < N and 0 <= ny < N:
word+= info[nx][ny]
else:
break
if word == 'MOBIS':
cnt += 1
print(cnt)
```
- 열심히 풀었음
> [Solve] : [BOJ] 31924 - 현대모비스 특별상의 주인공은? 2

- minsun/BOJ/1543/sol.py
- 내용 : [문제 링크](https://www.acmicpc.net/problem/1543)
```python
arr = input()
find_str = input()
index = 0
cnt = 0
for i in range(len(arr)):
if index > i:
continue
if find_str == arr[i:i+len(find_str)]:
cnt += 1
index = i + len(find_str)
print(cnt)
```
- 프린트함
> [Solve] : [BOJ] 1543 - 문서 검색 문제해결
